### ISSUE TITLE
ASPEM VARESE - stage - errore in controllo RdA diretta

### ISSUE THREAD

**Issue by LucZec** [DanRic/Bonus-idrico#10]
Su ASPEM VARESE in ambiente di stage, una volta acquisita la RdA diretta, non riesco a passare la fase di controllo; la segnalazione che vedi sul controllo della RdA in allegato, ce l’ho per ogni RdA individuale che acquisisco. Allego la RdA, il log dell'acquisizione, il log del controllo, la print della parametrizzazione SGATE.
[RdA_LZ008.zip](https://github.com/DanRic/Bonus-idrico/files/2529264/RdA_LZ008.zip)
![immagine](https://user-images.githubusercontent.com/44605609/47713439-9329bc80-dc3a-11e8-8d44-c051349d59a4.png)

**Comment by DanRic** [comment]
Ciao,
sembra che l'indirizzo _VIA CACC. DELLE ALPI_ non sia presente a sistema, o almeno non è presente su quel comune/cap/civico.
Hai verificato che il servizio 36441583 che hai inserito abbia quell'indirizzo?

**Comment by LucZec** [comment]
Il servizio 36441583 è su istat/cap/indirizzo/civico inserito nella RdA.

**Comment by LucZec** [comment]
Ho notato (ma magari è normale) che sulla tabella SIU_SGATE_SERV_ASS_RDA, abbiamo questa situazione
![immagine](https://user-images.githubusercontent.com/44605609/47722411-ac3e6780-dc52-11e8-997e-2b1c9d5d37ec.png)
mentre sulla RdA e su DB abbiamo "VIA CACC. DELLE ALPI"

**Comment by LucZec** [comment]
per la RdA "RdA_LZ009.xml", ho fatto una prova in questa modo: sulla tabella SIU_SGATE_RICH_AGEV ho modificato il campo RAS_AREA da "VIA MANZONI" in "MANZONI" (uguale al valore presente sulla tabella SIU_SGATE_SERV_ASS_RDA per il puntopresa 3216962); in questo modo ora la RdA passa il controllo e va nello stato "ACCETTATA". Su SIU_SGATE_RICH_AGEV ho ripristinato il valore "VIA MANZONI".

**Comment by LucZec** [comment]
allora...sul siu_sgate_controlli_rda.estrai_dati_controlli viene esguita su desvie la select nvl(dvi_des_100, dvi_des_30); purtroppo su ASPEM VARESE ho la situazione seguente su desvie

![immagine](https://user-images.githubusercontent.com/44605609/47731167-db110980-dc63-11e8-98ee-b0b15fd1732b.png)

quindi risolvo momentaneamente mettendo sulla RdA "CACC. DELLE ALPI"; ma non sappiamo se da SGATE la RdA arriverà con "VIA CACC. DELLE ALPI" o "CACC. DELLE ALPI". Grazie. Spero di essre stato chiaro.

**Comment by DanRic** [comment]
La situazione da te descritta viene risolta nel re-work dove possiamo dare una percentuale (%) di coincidenza con la via che ci manda SGAte. In tal caso, parametrizzando una percentuale dell'80% accetta anche le via del tuo caso di test.
Attualmente l'unico cliente che ha il re-work è **CCAM**.
Purtroppo nel primo rilascio la via deve combaciare perfettamente con quella presente a sistema.
Chiudo l'anomalia, nel caso puoi continuare a scrivere qui se anche dopo l'installazione del re-work il problema persiste.

**Comment by LucZec** [comment]
Grazie della spiegazione e scusa se torno sull'argomento e poi chiudiamo. Solo per capire meglio io e poter essere chiaro con il cliente (scusa l'ignoranza, ma non conosco le tempistiche): per re-work si intende un aggiornamento della Fase1 o la Fase2? Se aggiornamento della Fase1, immagino che lo avranno in produzione giusto? (altrimenti le RdA non passeranno mai il controllo)
Se Fase2, fino a quando non la avranno in produzione, allo stesso modo non riusciranno ad elaborare le RdA.
Grazie

**Comment by DanRic** [comment]
Si, è un aggiornamento della fase1. 
Purtroppo non è in fase di test in stage di CCAM, quindi per la produzione c'è da attendere ancora un po.
