### ISSUE TITLE
Ripristino massivo

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#100]
Ciao,
il ripristino massivo funziona, c'è una imperfezione sul primo flag, quello per selezionare tutte le RdA. Se lo seleziono e poi premo il pulsante "Ripristina", le RdA vengono ripristinate ma il flag rimane checkato.
Puoi levare il check dopo che ha ripristinato le RdA?

**Comment by SteLancio** [comment]
Ciao,
ho installato in ambiente svilh2o una correzione. Verifica se adesso è ok così in caso installo dal cliente.

**Comment by SteLancio** [comment]
Ho fatto un test e funziona. Ho installato la modifica dal cliente.
