### ISSUE TITLE
Gestione Richieste di Agevolazione

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#15]
Durante la ricerca impostando un filtro ( es. "ATTESA ESITO" ) si verifica l'errore in allegato.

**Comment by DanRic** [comment]
Per il metodo di allegamento file ti ho risposto qui https://github.com/DanRic/Bonus-idrico/issues/16#issuecomment-436271448

**Comment by DanRic** [comment]
Allego il file che non sei riuscito a caricare:
[BONUS_F1BIS_STATO_FORNITURA_20181106.docx](https://github.com/DanRic/Bonus-idrico/files/2553590/BONUS_F1BIS_STATO_FORNITURA_20181106.docx)

**Comment by ClaudioSalerno** [comment]
avevo allegato file sbagliato.
riprovo. ( non mi fa vedere il file allegato ! ) 
Ho provato sia con drag & drop che con selecting item

**Comment by ClaudioSalerno** [comment]
avevo allegato file sbagliato.
riprovo. ( non mi fa vedere il file allegato ! ) 
Ho provato sia con drag & drop che con selecting item

**Comment by SteLancio** [comment]
Ciao Claudio,
c'era un problema di parametrizzazione degli stato dell'RdA. 

In particolare:

![image](https://user-images.githubusercontent.com/44225241/48141641-94e32800-e2ab-11e8-855f-575917abc0a4.png)

In generale tutti gli stati hanno una situazione sporca:

![image](https://user-images.githubusercontent.com/44225241/48141994-3c605a80-e2ac-11e8-9d31-785808912bb9.png)

Ho provveduto a bonificare e riportare gli stati corretti:

![image](https://user-images.githubusercontent.com/44225241/48142049-5732cf00-e2ac-11e8-8595-09f7b4d29e8d.png)

Per evitare che si possa verificare lo stesso problema su altri clienti o in fase di passaggio in produzione, tale bonifica sarà eseguita in automatico in fase di installazione patch.

Fammi sapere se posso chiudere questa segnalazione.

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
Il filtro ora funziona. 
Non ho capito la questione degli STATI RdA "sporchi" ( c'erano dei record doppi/tripli ? ) .
CIò si è verificato con l'installazione della F1 Bis oppure è una situazione che ci troviamo anche nella F1 ?

**Comment by ClaudioSalerno** [comment]
se sei daccordo, andrebbe cambiato lo stato della issue che non dovrebbe essere "respinta" ma "bug" dovuto ad installazione.

**Comment by SteLancio** [comment]
Potrebbe essere legata all'installazione degli sviluppi della fase 1. Si tratta di dati sporchi legati al fatto che manca l'indice univoco sulla tabella. Tale indice verrà creato in automatico in fase di installazione della nostra patch fase 1.

Sono d'accordo con il cambio di stato della issue. Provvedo a modificarlo.

Grazie

**Comment by ClaudioSalerno** [comment]
si grazie si può chiudere.
