### ISSUE TITLE
Verifica STATO FORNITURA

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#16]
in fase di TEST 3 per il controllo dello STATO FORNITURA, rilevo il seguente comportamento :                        
Per i dettagli vedere allegato.

Tipologia : Utente DIRETTO

Param:
 

Fornitura: 
 
Acquisizione:
 

Controllo:
 

Eseguendo il “Controllo” mi sarei aspettato che la richiesta rimanesse in “ACQUISITA” dato che la sysdate è < del 01/12/2018 ed invece la richiesta è evoluta in “ACCETTATA”

Inserisco la segnalazione in GitHub , nel frattempo mi aiutate a capire se sbaglio io oppure c’è qualche cosa che non va ?

Grazie per la collaborazione

**Comment by DanRic** [comment]
Ciao Sergio.
Il word che hai inserito non si vede. Che estensione ha il file?
Puoi caricare un file word.docx.
Se è .doc non lo accetta.
Per tutti i file che non vengono accettati puoi creare una cartella.zip, metterci dentro tutti i tipi di file che vuoi e caricarlo qui trascinandolo nella finestra di chat.

[File.docx](https://github.com/DanRic/Bonus-idrico/files/2553549/File.di.prova.per.github.docx)

[File.zip](https://github.com/DanRic/Bonus-idrico/files/2553554/File.di.prova.per.github.zip)

**Comment by SteLancio** [comment]
Ciao Claudio,
puoi verificare se la casistica che hai testato rientra nella seguente logica prevista dal controllo “STATO_FORNITURA”?

Il servizio con bonus viene sottoposto ai seguenti controlli:

•	se “allineamento” non presente oppure ‘N’ (flag allineamento su xml rda)  si esegue il controllo:
se datainizioagevolazione” sia <= sysdate si controlla anche che la data inizio fornitura sia <= dataInizioAgevolazione e minore anche della < data fine fornitura:
o	Se la fornitura non è attiva si restituisce esito = KO codErrSiu = 102, altrimenti esito = OK; 
•	se invece “allineamento” = True  (flag allineamento su xml rda)  si esegue il controllo: 
o	se sysdate < data_limite_validazione  la richiesta RDA rimane in ACQUISITA
o	se sysdate >= data_limite_validazione  la richiesta RDA restituisce esito = KO codErrSiu = 102


Fammi sapere.

Grazie,
Stefano

**Comment by SteLancio** [comment]
Ciao Claudio,
ho eseguito ulteriori verifiche e, oltre alle logiche sotto indicate, attualmente  il controllo viene eseguito se:
data inizio agevolazione < data inizio forn >= data fine forn.

Nell’ultimo caso che m’ hai indicato la data di inizio fornitura del servizio è:
 
![image](https://user-images.githubusercontent.com/44225241/48072520-fdaf9f00-e1dc-11e8-93e3-529ee293f6d0.png)

Mentre la data inizio agevolazione:
 
![image](https://user-images.githubusercontent.com/44225241/48072402-b45f4f80-e1dc-11e8-9d67-dae625f835a5.png)

Pertanto il controllo restituisce esito positivo.

Ciao,
Stefano

**Comment by ClaudioSalerno** [comment]
Ciao Stefano,

ti confermo che il caso evidenziato in giallo  scatta nel momento in cui ho la data inizio fornitura >= data inizio agevolazione e la sysdate < della data limite.

Ho creato il caso di test CSTEST3006 con :
•	data inizio fornitura: 10/08/2018
•	data fine fornitura: NULL
•	data inizio agevolazione : 01/07/2018
•	data limite : 01/12/2018

Eseguendo il controllo lo stato rimane in : ACQUISITA.

Vi sottopongo però una questione …

Fermo restando le condizioni di cui sopra ad eccezione della data limite ( anticipandola al 01/11/2018 in modo che sia > della sysdate ) , la RdA va in KO2 per Servizio NON ATTIVO in data inizio agevolazione
 

Ma indipendentemente dalla data limite ( 01/11 o 01/12 ) alla quale si fa il controllo , la fornitura attivata il 10/08/2018, è comunque attiva ed il flag “allineamento” a true indica che la fornitura va considerata attiva indipendentemente dalla data di inizio fornitura ( in questo caso successiva alla data di inizio agevolazione).

Riporto un esempio presente nell’Allegato A del DACU:
Domanda idrica presentata il 16 luglio 2018, ammessa dal Comune il 18 luglio e trasferita in pari data al gestore, il gestore per la validazione ha a disposizione il periodo compreso fra il 18 luglio ed il 1 settembre giorno in cui deve restituire un esito a SGAte. Il richiedente risulta già titolare di bonus elettrico e/o gas con periodo di agevolazione 1 maggio 2018 al 30 aprile 2019, la fornitura idrica è attiva al 1 settembre 2018, ma non era attiva all’1 maggio 2018. Il periodo di agevolazione idrico sarà allineato a quello elettrico e gas, quindi la data inizio agevolazione sarà anche per l’idrico il 1 maggio 2018 indipendentemente dal fatto che a quella data la fornitura idrica fosse attiva o no.

A mio avviso nel controllo va considerata anche la data di fine fornitura ( in questo caso NULL e quindi attiva ).

Scusate il ragionamento contorto .. forse mi sto impicciando … chiedo anche l’aiuto delle colleghe in copia.

**Comment by SteLancio** [comment]
Ciao Claudio,
è corretto quello che dici ed in accordo con Daniele abbiamo modificato le condizioni di logica sul controllo. 
Ho appena installato un’adeguamento.

Facci sapere.

Grazie.
Stefano

**Comment by ClaudioSalerno** [comment]
Ciao, 
ho rieseguito il TEST ( protocollo CSTEST3007BIS ). 
La richiesta va in KO 2 ( La fornitura non risulta attiva).

**Comment by SteLancio** [comment]
Ho visto che la modifica installata ieri non era presente stamane. Ho reinstallato nuovamente. 
Riprova e fammi sapere se adesso funziona come atteso.

Grazie

**Comment by ClaudioSalerno** [comment]
allora ... il caso con prot. CSTEST3007BIS  ( data limite 01/11/2018 , data inizio forn 10/08/2018, data finforn NULL, data iniagev 01/07/2018  , va in RIFIUTATA ,  invece dovrebbe essere ACCETTATA. Purtroppo non va bene ... 

Caso di test con prot. CSTEST3006 , stesse date , ma la data limite è 01/12/2018, lo stato RdA rimane in ACQUISITA e questo va bene

**Comment by SteLancio** [comment]
Ho appena installato un adeguamento che dovrebbe andare bene in entrambi i casi indicati.
Riprova tutte le casistiche che hai finora testato con allineamento = TRUE e fammi sapere.

Grazie

**Comment by ClaudioSalerno** [comment]
entrambe le richieste ora vanno bene. grazie

**Comment by ClaudioSalerno** [comment]
concordo. si può installare la nuova versione. mi riservo di fare delle verifiche.

**Comment by SteLancio** [comment]
Installazione appena eseguita.

Fammi sapere.

Ciao,
Stefano

**Comment by ClaudioSalerno** [comment]
le due richieste ora vanno bene, Entrambe essendo su forniture atrtive, indipendentemente dalla data limite , vanno in ACCETTATA. mi viene però un dubbio, se sia corretto, inviare un esito a SGAte prima della data limte.
 In pratica , se ho impostato la data limite al 01/12/2018 e oggi controllo una RdA ( con flag allineamento = true) di una fornitura Attiva, l'RdA mi va in Accettata . 
Se eseguo un invio file esiti a SGAte, anche di questa richiesta, è corretto ? 
SGAte la accetta visto che sto inviando un esito di una richiesta prima della scadenza del terrmine ( 01/12/218 ) ?

**Comment by DanRic** [comment]
@ClaudioSalerno Possiamo chiudere l'anomalia?

**Comment by ClaudioSalerno** [comment]
si grazie. si può chiudere
