### ISSUE TITLE
Filtro Data Limite su GRDA

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#17]
In ASR è riportato:
[..]
La data “calcolata” , ovvero “primo giorno del secondo mese successivo alla data disponibilità” deve essere memorizzata sull’RdA ed utilizzata come filtro per l’estrazione dati dal Cruscotto delle RdA. ( Gestione Richieste di Agevolazione )
In fase di estrazione verranno estratte tutte le RdA che avranno una data “calcolata” <= alla data di sistema.
[..]
Nella form non trovo questa data limite tra i filtri.

Grazie
Claudio

**Comment by SteLancio** [comment]
Ciao Claudio,
ho verificato che il filtro indicato effettivamente manca.
Ti aggiorno non appena avrò installato l'adeguamento con il filtro data limite.

Grazie,
Stefano

**Comment by SteLancio** [comment]
Ciao Claudio,
Installazione appena eseguita.
Riprova e fammi sapere se adesso il filtro sulla data limite è correttamente visibile e funzionante.

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
credo che non vada bene ... hai applicato la condizione di uguaglianza ... a mio avviso dovrebbero  essere estratte tutte le RdA con data limite<= data limite impostata.
L'obiettivo del filtro è quello di essere di aiuto all'operatore di verificare quali sono le RdA da controllare ad una certa data. 
Ad esempio se imposto come data limite quelle odierna, mi aspetto che vengano estratte tutte le RdA con data limite <= sysdate.

**Comment by ClaudioSalerno** [comment]
Ho risposto direttamente nel commento della issue

Da: SteLancio [mailto:notifications@github.com]
Inviato: martedì 6 novembre 2018 17:49
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] Filtro Data Limite su GRDA (#17)


Ciao Claudio,
Installazione appena eseguita.
Riprova e fammi sapere se adesso il filtro sulla data limite è correttamente visibile e funzionante.

Grazie,
Stefano

**Comment by SteLancio** [comment]
Ok, modificato il filtro nel seguente modo --> RdA con data limite<= data limite impostata.

**Comment by ClaudioSalerno** [comment]
Il filtro lavora correttamente. la segnalazione può essere chiusa. grazie
