### ISSUE TITLE
CCAM F1Bis - Trovati piu' servizi sugli indirizzi forniti

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#18]
[TEST F1 Bis.zip](https://github.com/DanRic/Bonus-idrico/files/2558392/TEST.F1.Bis.zip)

Ho ricreato il caso di TEST ( protocollo: CSTEST1004BIS ).

Ho dovuto però fare  una forzatura sull’anagrafica cambiando nome e cognome ad una delle forniture. 
Cmq è un caso che ci può stare che una anagrafica abbia 2 forniture con stessa intestazione.

In pratica ho identificato 2 forniture attive (7043008 , 2958601 ) che sono sulla stessa Via e Civico  (VIA MAZZINI, 37 ).
La prima fornitura (7043008 ) con codana ( 72621) è associata a MARIO MASSA
La seconda fornitura (2958601) con codana (20199) è associata a BRUNO AMELI.

In Gesana ho cambiato il nome e cognome di BRUNO AMELI in MARIO MASSA.
Sul file RdA , associato a MARIO MASSA non ho inserito il codice utente ( ho messo tutti zeri) .

La richiesta in fase di controllo è andata in RIFIUTATA:
 
Con la seguente motivazione:
 

Allego file XML e log .

**Comment by SteLancio** [comment]
Ho ripetuto il controllo ripristinando l'RdA e nel mio caso è andata correttamente in "IN VERIFICA":

![image](https://user-images.githubusercontent.com/44225241/48148754-cd3e3280-e2ba-11e8-8b1c-975f20a58c48.png)

Anche il file che viene prodotto contiene un errore di tipo W:

![image](https://user-images.githubusercontent.com/44225241/48148792-e8a93d80-e2ba-11e8-8ba9-b32ac6bb0475.png)

Non vorrei che ti sei incartato magari.

**Comment by SteLancio** [comment]
Riprova e fammi sapere

**Comment by ClaudioSalerno** [comment]
confermo la risoluzione. 
la segnalazione può essere chiusa. grazie.
