### ISSUE TITLE
CCAM: F1BIS Gestione Rich Agev pulsante 'S'

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#19]
Il pulsante S della form Ricieste di Agevilazione,  estrae i dati dalla tabella SIU_SGATE_SERV_ASS_RDA. 
Cortesemente verificare se nella where condition viene utilizzato l'UTE. 
La richiesta proviene da un controllo su un cambio forzato del campo SAR_UTE valorizzato a CS anzichè 01.
ma il record viene visualizzato lo stesso.
vedere allegato.

[CSTEST3001.zip](https://github.com/DanRic/Bonus-idrico/files/2561141/CSTEST3001.zip)

Grazie

**Comment by SteLancio** [comment]
Ciao Claudio,
ho appena installato un adeguamento che dovrebbe risolvere il problema che hai appena segnalato.

Fammi sapere.

**Comment by ClaudioSalerno** [comment]
La correttiva va bene. 
La segnalazione si può chiudere.
Grazie
