### ISSUE TITLE
CCAM F1BIS - Controllo RdA Centralizzata - Verifica presenza forn rete Gestore

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#20]
Ciao,
in fase di controllo delle RdA con prot. CSTESTCOND002 , mi viene segnalato il seguente errore:
"La fornitura non risulta presente nella rete del gestore"

premetto che nella via presente nell'RdA - VIA OLLEARO ci sono forniture.
Tra l'altro al civico 1, c'è proprio un Condominio ( CONDOMINIO FERRARIS ).

E' possibile fare una verifica ?
Quali sono le condizioni di ricerca in questo caso , dato che anche la Deniminazione Condominio coincide con l'anagrafica della fornitura ?

**Comment by DanRic** [comment]
Ciao Claudio, 
puoi fornirci l'xml che stai acquisendo?
Grazie

**Comment by ClaudioSalerno** [comment]
[CSTESTCOND002.zip](https://github.com/DanRic/Bonus-idrico/files/2561619/CSTESTCOND002.zip)

**Comment by SteLancio** [comment]
Ho verificato che il servizio presente sull'indirizzo non viene trovato in quanto subentrato:

![image](https://user-images.githubusercontent.com/44225241/48211118-1785e900-e379-11e8-95c0-736d5f166cf5.png)

Il comportamento è corretto.

Fammi sapere se posso chiudere la issue.

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
Ciao,
la forntura ( 7443940) associata all'anagrafica CONDOMINIO FERRARIS mi risulta Attiva e NON subentrata.
select ser_puntopresa, ser_statoserv, ser_stato_cont, ser_codana, ana_nome, ana_cognome, ana_ragsoc, dvi_des_30, ser_ucnumciv, ser_ucsuffisso,ana_codfis
from serviz , gesana, desvie
where ser_ute = '01' and ser_codser = 3
and ser_ute = ana_Ute
and ser_codana = ana_codana
and ser_ucsigloc = 89 and ser_ucsigvia = 436
and ser_ucnumciv = 1
and ser_statoserv = 1
and ser_ute = dvi_ute
and ser_ucsigvia = dvi_sigvia

E' possibile verificare ?
Grazie

**Comment by SteLancio** [comment]
Ho verificato che la fornitura attiva è su scala A

![image](https://user-images.githubusercontent.com/44225241/48266696-6b073e00-e430-11e8-8591-f93ced479d0d.png)

Mentre nell'xml che hai caricato c'è 3. 
Pertanto non andava a trovare quella corretta subentrata.

Fammi sapere se posso chiudere la issue.

Grazie

**Comment by SteLancio** [comment]
Ciao Claudio,
non ho avuto poi riscontro in merito a questa segnalazione. Può essere chiusa?

Fammi sapere.

**Comment by SteLancio** [comment]
Ti confermo che se nel file xml vengono passati anche interno e scala --> questi elementi vengono utilizzati per identificare la fornitura. 
Mentre il suffisso non viene gestito nel nostro sistema.

Fammi sapere.

**Comment by ClaudioSalerno** [comment]
Il suffisso è l'estensione al civico. ( ser_ucsuffisso )

cmq la segnalazione si può chiudere. 
Grazie
