### ISSUE TITLE
CCAM : F1 Bis - Errore Acquisizione XML

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#21]
Non riesco ad acquisire il file in allegato per un errore di XML invalido.
Per cortersia potete verificare ?
Grazie
[TEST 1 F1 Bis.zip](https://github.com/DanRic/Bonus-idrico/files/2562113/TEST.1.F1.Bis.zip)

**Comment by SteLancio** [comment]
Nei log che hai allegato non vedo un errore su xml invalido ma vedo:

![image](https://user-images.githubusercontent.com/44225241/48205364-67aa7e80-e36c-11e8-95e9-ab23f34e5061.png)

Forse hai sbagliato allegato?

**Comment by ClaudioSalerno** [comment]
all'interno del file .zip c'è un xml ed un png

**Comment by SteLancio** [comment]
Nell'xml che hai inviato il tag del civico è sbagliato:

![image](https://user-images.githubusercontent.com/44225241/48205718-f6b79680-e36c-11e8-8e2e-228b1a1db160.png)

Ti allego quello corretto:

[CSCOND003tris.zip](https://github.com/DanRic/Bonus-idrico/files/2562157/CSCOND003tris.zip)

**Comment by ClaudioSalerno** [comment]
grazie. ma non è possibile mettere questa informazione nel log in modo da rendrlo più parlante?

**Comment by SteLancio** [comment]
In questo caso no, perchè il problema è che il file inviato non è un xml formalmente corretto. Il messaggio di errore che viene dato è corretto.

Fammi sapere se posso chiudere la issue.

**Comment by ClaudioSalerno** [comment]
grazie la segnalazione può essere chiusa.
