### ISSUE TITLE
CCAM: F1BIS - utenza diretta - Verifica fornitura nella rete del gestore

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#22]
In fase di controllo sulla rchiesta con prot. CSTEST1018BIS

viene segnalato il seguente errore:
siu_sgate_automatismi.Esegui_controlli_RDA(POS:Apertura cursore Controlli PDR Diretti)() - Errore Generico: ORA-06508: PL/SQL: could not find program unit being called

e la richiesta va in RIFIUTATA

**Comment by SteLancio** [comment]
Scusami, colpa mia! Stavo installando un piccolo adeguamento (non legato alle tue segnalazioni).
Puoi uscire dalla procedura e riprovare?

Grazie

**Comment by ClaudioSalerno** [comment]
si si sgraze .. .ci ho pensato dopo aver aperto la segnalazione. 
Già fatto.
la segnalazione può essere chiusa.
Garzie mille
