### ISSUE TITLE
CCAM: F1 BIS - Errore Acquisione XML

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#23]
Ciao, acquisendo il file in allegato il sistema segnala il seguente errore nel log:

 (ORA-31011: XML parsing failed

ORA-19202: Error occurred in XML processing
LPX-00209: PI names starting with XML are reserved
Error at line 1)
[TEST F1 Bis - Errore Acquisione XML.zip](https://github.com/DanRic/Bonus-idrico/files/2566530/TEST.F1.Bis.-.Errore.Acquisione.XML.zip)

segnalo che si tratta della prima acquisiione dopo l'aggiornamnto del programma.

**Comment by ClaudioSalerno** [comment]
aggiungo che nel file CSTESTCOND005 ho tolto il campo "scala" mentre nel secondo file CSTESTCOND005BIS l'ho inserito ma impostando 0 nel valore

**Comment by SteLancio** [comment]
Ciao Claudio,
il problema è stato risolto. 

Dopo un ferrato debug abbiamo capito che l'encoding dell'xml prodotto in fase di caricamento sul db del cliente era differente rispetto al nostro internamente.

Fammi sapere.

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
Ok
Appena arrivo a casa faccio una prova .

Grazie mille
Ciao
Claudio



Inviato dal mio dispositivo Huawei

-------- Messaggio originale --------
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - Errore Acquisione XML (#23)
Da: SteLancio
A: DanRic/Bonus-idrico
CC: Salerno Claudio ,Author


Ciao Claudio,
il problema è stato risolto.

Dopo un ferrato debug abbiamo capito che l'encoding dell'xml prodotto in fase di caricamento sul db del cliente era differente rispetto al nostro internamente.

Fammi sapere.

Grazie,
Stefano

**Comment by SteLancio** [comment]
Chiudo la segnalazione.

Grazie
