### ISSUE TITLE
CCAM: F1 Bis - Esposizione nuovi campi in form Gest Rich Agev

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#24]
Nella form non vengono visualizati i campi "allineamento", "fruizionecontinuativa", "edificioplurifamiliare" .
Le informazioni sono in tabella ( siu_sgate_rich_agev ), ma non sono visibili nella parte di dettaglio della form.

E' possibile inserirli ?

Grazie

**Comment by SteLancio** [comment]
La consultazione di quei campi non era stata definita in AF. Vediamo se riusciamo a inserire questa modifica in coda alle anomalie.

Ciao,
Stefano

**Comment by SteLancio** [comment]
Ciao Claudio,
con l'ultimo aggiornamento installato, anche i campi:
"allineamento", "fruizionecontinuativa", "edificioplurifamiliare"  verranno visualizzati sulla form.

Fammi sapere se posso chiudere questa segnalazione.
Grazie

**Comment by ClaudioSalerno** [comment]
ciao,
ho visto che i campi indicato sono visibili in form Gstione Richieste, ma come mai eè stata utilizzata una modatà diferente rispetto agli altri campi ? Estetcamente non è il massimo , anzi, C'eè un vincolo tecnico ? se si quale ? E' possibile visualizzarli alla stessa modalità degli altri ?

Grazie

**Comment by SteLancio** [comment]
Sono stati inseriti i campi di tipo check box (ovvero flag) perchè il valore di queste colonne può essere S ("TRUE" nell'xml) o N ("FALSE"). Come alternativa al flag è possibile visualizzare direttamente il valore S o N se preferisci. 

Fammi sapere.
Grazie

**Comment by ClaudioSalerno** [comment]
Ciao,
i flag non vanno cambiati ma semplicemente visualizzati per cui non è necessario il check box.

Grazie
Claudio

Da: SteLancio [mailto:notifications@github.com]
Inviato: lunedì 19 novembre 2018 10:44
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 Bis - Esposizione nuovi campi in form Gest Rich Agev (#24)


Sono stati inseriti i campi di tipo check box (ovvero flag) perchè il valore di queste colonne può essere S ("TRUE" nell'xml) o N ("FALSE"). Come alternativa al flag è possibile visualizzare direttamente il valore S o N se preferisci.

Fammi sapere.
Grazie

**Comment by SteLancio** [comment]
Ok, modifica appena installata.

Fammi sapere se posso chiudere questa issue.

**Comment by ClaudioSalerno** [comment]
Ok grazie.

Ora i campi vengono visualizzati correttamente.

La segnalazione si può chiudere.

Da: SteLancio [mailto:notifications@github.com]
Inviato: lunedì 19 novembre 2018 11:05
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 Bis - Esposizione nuovi campi in form Gest Rich Agev (#24)


Ok, modifica appena installata.

Fammi sapere se posso chiudere questa issue.
