### ISSUE TITLE
CCAM: F1 Bis - Acquisizione esiti da SGAte

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#25]
[TEST F1 Bis-Esiti_da_Sgate.zip](https://github.com/DanRic/Bonus-idrico/files/2571364/TEST.F1.Bis-Esiti_da_Sgate.zip)

Acquisendo il file degli esit in allegato, la riceista rimane in ATTESA ESITO e nel logo no viene segnalato nulla.

**Comment by ClaudioSalerno** [comment]
aggiungo che acquisendo l'esito di un altro file , per un'altra richiesta ( CSTEST014BIS ), ho lo stesso risultato. ovvero non viene segnalato nulla nel log , l'esito rimane in ATTESA ESITO e nei totalizzatori della form rimane tutto a zero.

**Comment by SteLancio** [comment]
Ho appena installato una correzione che dovrebbe risolvere il problema segnalato. 

Fammi sapere.

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
ora funziona. Grazie

**Comment by SteLancio** [comment]
Posso chiudere la segnalazione quindi?

**Comment by ClaudioSalerno** [comment]
si la segnalazione può essere chiusa. grazie
