### ISSUE TITLE
La form Definizione Parametri dei Controlli contiene valori errati

### ISSUE THREAD

**Issue by fidore** [DanRic/Bonus-idrico#26]

**Comment by fidore** [comment]
La form contiene dei parametri doppi e con valori anche diversi tra loro, vedi allegato.


![def_param_contr_ccam](https://user-images.githubusercontent.com/44232872/48355867-45c73980-e695-11e8-8152-54a92aa3331d.PNG)

**Comment by fidore** [comment]
Scusate, ho sbagliato a chiudere

**Comment by SteLancio** [comment]
Ho corretto il problema eliminando le righe doppie ed installato l'indice sulla tabella che impedisce che si possa verificare tale duplicazione.

Fammi sapere se posso chiudere la segnalazione.

**Comment by SteLancio** [comment]
A quali ti riferisci in particolare? Puoi inviarmi una print?

**Comment by fidore** [comment]
![image](https://user-images.githubusercontent.com/44232872/48357507-11ee1300-e699-11e8-95ab-00f6a579e987.png)

**Comment by DanRic** [comment]
Ciao @fidore la parametrizzazione va bene.
Cosa non ti torna?

**Comment by fidore** [comment]
Che dovrebbero essercene alcuni in +

**Comment by DanRic** [comment]
Gli altri, tipo Esiste_Nome, sono stati inglobati dentro Trova Fornitura.
Molti dei controlli vecchi sono stati eliminati o inglobati. 
La cosa è dovuta al fatto che SGAte è eliminato dei messaggi di KO; per esempio non esiste più il KO per "nome/cognome non corrispondente".

**Comment by fidore** [comment]
Va bene, grazie. Chiudi pure se vuoi.
