### ISSUE TITLE
CCAM: F1BIS- Verifica piu servizi ( catena Subentri)

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#27]
Ciao, 
segnalo il seguente caso:
Fornitura attiva: 35957694 il 05/11/2018 subentrata alla fornitura 4405416 ( cessata il 04/11/2018 ) stessa anagrafica ( 2457)
Inizio agevolazione : 10/09/2018
Mi sarei aspettato un OK con difformità per il codice utente oppure un OK perchè cmq , al di la del codice fornitutra, l'anagrafica è la stessa e c'è anche stata continuità ( tra il subentrato ed il subentrante)

4405416  inifor 01/07/2001 fin form 04/11/2018 
35957694  inifor 05/11/2018 finfor NULL

IL sistema segnala:

102: siu_sgate_controlli_rda.piu_servizi - Servizio non attivo in data inizio agev. (10/09/2018)
102: La fornitura non risulta attiva
allego xml e log.
[TEST 4 step 7 F1 Bis.zip](https://github.com/DanRic/Bonus-idrico/files/2575695/TEST.4.step.7.F1.Bis.zip)

**Comment by SteLancio** [comment]
Ciao Claudio,
ho visto che i collegamenti sono tutti e 3 occupati. Come posso collegarmi per fare delle verifiche in merito a questo problema?

**Comment by ClaudioSalerno** [comment]
Puoi temporaneamente utilizzare eng_sup2 / 2h,a7dfr

La sto utilizzando io … ma per un po te e lascio ( se non ti prende molto tempo )

Da: SteLancio [mailto:notifications@github.com]
Inviato: martedì 13 novembre 2018 15:56
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1BIS- Verifica piu servizi ( catena Subentri) (#27)


Ciao Claudio,
ho visto che i collegamenti sono tutti e 3 occupati. Come posso collegarmi per fare delle verifiche in merito a questo problema?

**Comment by DanRic** [comment]
Ciao Claudio,
attualmente il sistema prende l'ultimo servizio attivo sull'indirizzo/anagrafica inviata da SGAte.
Non viene analizzato lo storico di tutti i servizi per verificare se ne troviamo uno che possa essere agevolato.
Tale logica dovrebbe essere analizzata e condivisa anche con il Billing.
Anche se tale logica fosse attiva non trovo corretto passare nell'RdA il puntopresa 35957694 (che trova riscontro positivo nel sistema del Gestore) e sperare che il sistema capisca che si deve prendere come date di riferimento quelle del servizio 4405416.

Forse può avere senso nei casi in cui ALLINEAMENTO = TRUE, perchè nei casi come questo, la data inizio agevolazione è sempre futura, quindi è inutile complicare la logica per casi che non si verificano. Però è sempre da analizzare/condividere e stimare.

**Comment by SteLancio** [comment]
Ciao Claudio,
ho appena installato un adeguamento che dovrebbe prevedere anche la casistica segnalata in questa issue.
Riprova e fammi sapere se adesso è ok.

Grazie,
Stefano

**Comment by DanRic** [comment]
@ClaudioSalerno Possiamo chiudere l'anomalia?

**Comment by DanRic** [comment]
Ciao ho inserito una correzione.
Puoi rifare un test e farmi sapere se adesso funziona?

**Comment by ClaudioSalerno** [comment]
Ciao, ho eseguito il seguente test con esito positivo: TEST4STEP7  prot. Rich: CSTEST4STEP7QUAD

Caso: Subentro su stessa anagrafica

Dati:
Fag allineamento : false/null
data ini agev: 01/07/2018
Anagrafica: 7474
Fornitura Attiva 4837973 date originali : ini 26/03/2003: fin: NULL
Fornitura subentrata 1915344 ini:26/04/1977  fin 26/03/2003

data forzate su ATTIVA: ini 15/08/2018 fi null
SUBENTR fin 15/08/2018

Esito: viene selezionata correttamente la fornitura attiva (4837973 ) anche se la data di inizio forn è > data ini agev.
il calcolo del bonus Una Tantum viene eseguito correttamente dal 01/01/2018 al 30/06/2018

Mi riservo di eseguire un altro test con altre date e con flag allineamento a True.

claudio

Da: Claudio Salerno [mailto:Claudio.Salerno@eng.it]
Inviato: mercoledì 21 novembre 2018 23:25
A: 'DanRic/Bonus-idrico'; 'DanRic/Bonus-idrico'
Cc: 'Mention'
Oggetto: R: [DanRic/Bonus-idrico] CCAM: F1BIS- Verifica piu servizi ( catena Subentri) (#27)

Ciao,
per il test avevo forzato i dati e poi l’ho ripristinati per cui ora trovi i valori originari



Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 21 novembre 2018 18:26
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Mention
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1BIS- Verifica piu servizi ( catena Subentri) (#27)


Ciao Claudio, stavo facendo dei test.
Mi sembra che alla fornitura 4405416 sia subentrata la 6564472 (non la 35957694)
e di conseguenza 35957694 non penso che sia subentrata alla 4405416.
Controlli e mi fai sapere?

**Comment by SteLancio** [comment]
Ciao Claudio,
mi confermi che è possibile chiudere questa segnalazione?
