### ISSUE TITLE
CCAM: F1 Bis - Ricerca fornitura con suffisso sull'indirizzo

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#29]
ho eseguito il test richiesto.

Il campo suffisso, se presente nel tag civico viene correttamente riportato in un campo a parte e visualizzato nella form Gestione Richieste Agevolazione, ma il campo sembrerebbe non essere preso in considerazione per la ricerca.

Es. UTENZA CETRALIZZATA
Prot. Rich: 821284685
Indirizzo presente in RdA : VIA UMBERTO I 
Civico : 2/B

 

 

Il Controllo porta l’esito della RdA in ACCETTATA ed individua la fornitura: 36609921 che è sul civico 2 ( ma senza suffisso ). Tra l’altro si tratta di una utenza individuale e non di un condominio ( anche se in questa fase questo controllo non viene effettuato).
Per cui se si calcolasse il BONUS, si assegnerebbe ad una utenza/anagrafica che non centra nulla.

 

Tra l’altro al Civico 2 / B non c’è nessuna fornitura.
 

E’ possibile fare una verifica ?
Grazie
Claudio

**Comment by DanRic** [comment]
Ciao Claudio,
cosa intendi quando dici
> ma il campo sembrerebbe non essere preso in considerazione per la ricerca.

Vorresti che adesso anche il civico ed il suffisso vengano inseriti tra i campi in alto per ricercare l'RdA?
![issue](https://user-images.githubusercontent.com/43675808/48772449-b4734b00-ecc4-11e8-8fee-79012e73c204.png)

Per quanto riguarda il servizio trovato (36609921), questo è possibile perchè se il gestore non ha a sistema il suffisso (campo nullo), questo non viene considerato come non trovato.
Rimane comunque la coincidenza dei restanti campi: 
indirizzo ed eventuali dati anagrafici per individuare la fornitura, senza contare il codice fornitura che SGAte può inviarci corretto.

Se vuoi possiamo inserire il vincolo che suggerisci: se SGAte ci manda suffisso B il servizio deve avere solo e soltanto suffisso B, se campo non valorizzato esito KO: "servizio non trovato".

Analizzando i servizi attivi (1,1) sul cliente CCAM ho notato che il suffisso non è valorizzato per 38255 forniture in stage e  38229 in produzione.

Questi verrebbero tutti non trovati se SGAte ci manda il suffisso valorizzato.
Confermi che è giusto?

**Comment by ClaudioSalerno** [comment]
No,
intendo dire che l’indirizzo trovato non tiene conto del suffisso.

Nel caso specifico della segnalazione, rilevo che la fornitura alla quale è stata assegnata la Rda, è sul civico 2 ma non c’è nessuna fornitura al civico  2 / B, per cui l’RDA viene associato ad una fornitura non corretta. Tra l’altro questa fornitura è anche una fornitura individuale e non una centralizzata.

Io direi che se SGATE passa il suffisso è corretto che venga controllato ( domanda: è possibile inserire questo controllo sotto parametro in modo che sia opzionale ? ).

[cid:image003.jpg@01D480D3.2E73E8F0]

Da: DanRic [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 13:05
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 Bis - Ricerca fornitura con suffisso sull'indirizzo (#29)


Ciao Claudio,
cosa intendi quando dici

ma il campo sembrerebbe non essere preso in considerazione per la ricerca.

Vorresti che adesso anche il civico ed il suffisso vengano inseriti tra i campi in alto per ricercare l'RdA?
[issue]<https://user-images.githubusercontent.com/43675808/48772449-b4734b00-ecc4-11e8-8fee-79012e73c204.png>

Per quanto riguarda il servizio trovato (36609921), questo è possibile perchè se il gestore non ha a sistema il suffisso (campo nullo), questo non viene considerato come non trovato.
Rimane comunque la coincidenza dei restanti campi:
indirizzo ed eventuali dati anagrafici per individuare la fornitura, senza contare il codice fornitura che SGAte può inviarci corretto.

Se vuoi possiamo inserire il vincolo che suggerisci: se SGAte ci manda suffisso B il servizio deve avere solo e soltanto suffisso B, se campo non valorizzato esito KO: "servizio non trovato".

Analizzando i servizi attivi (1,1) sul cliente CCAM ho notato che il suffisso non è valorizzato per 38255 forniture in stage e 38229 in produzione.

Questi verrebbero tutti non trovati se SGAte ci manda il suffisso valorizzato.
Confermi che è giusto?

**Comment by DanRic** [comment]
Ciao Claudio,
il sistema tiene conto del suffisso.
Semplicemente se sul servizio che hai trovato non è stato inserito il suffisso, questo non viene scartato.
Sul servizio 36609921 non è presente il suffisso, se era presente veniva controllato:
![issue](https://user-images.githubusercontent.com/43675808/48777407-c52abd80-ecd2-11e8-913a-6c0da439c62e.png)

Quindi ripeto la domanda.
Se il gestore non ha allineato l'anagrafica dei suffissi nel suo sistema (molti sono nulli), vuoi comunque che io rifiuto (scarto) questi servizi perchè il suffisso deve essere sempre valorizzato?
Lo sviluppo dell'opzione codificata per gestire il suffisso non posso farla adesso, a test quasi chiusi.
Casomai ne riparliamo nella fase2.

**Comment by ClaudioSalerno** [comment]
Ciao,
allego la situazione con alcune considerazioni.
Premesso che il suffisso NON deve essere sempre valorizzato, ma semplicemente se presente nella RdA , lo utilizzo per cercare una fornitura a quell'ndirizzo ( completo) .
Se il suffisso non c'è nella RdA non lo utilizzo.
In sostanza utilizzo quello che mi viene passato nella RdA.

[Issue_29.docx](https://github.com/DanRic/Bonus-idrico/files/2604739/Issue_29.docx)

**Comment by DanRic** [comment]
Ciao ho inserito una correzione.
Puoi rifare un test e farmi sapere se adesso funziona?

**Comment by ClaudioSalerno** [comment]
Ciao,
i test sul suffisso funzionano ( nel senso che le forniture vengono individuate o no in relazione all’indirizzo fornito nella RdA che può avere o non avere il suffisso , così come nel DB).

Ho notato però che nel caso in cui nel suffisso viene passato “SN1” , oppure “SNC”   “Senza Numero Civico” , nel campo della tabella nel campo civico viene riportato -1.
E’ corretto ?

Nel caso in cui effettivamente non c’è il numero civico ( casi reali , su CCAM ce ne sono una ventina ) e nella Rda viene passato appunto “SNC” , secondo me dovrebbe essere impostato nel suffisso e non mettere -1 sul civico.

Select t.ser_puntopresa, t.ser_ucnumciv, t.ser_ucsuffisso
  from serviz t
  where t.ser_ucsuffisso = 'SNC'
  and ser_ute = '01' and ser_codser = 3 and ser_statoserv = 1

Grazie
Claudio

Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 21 novembre 2018 18:03
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 Bis - Ricerca fornitura con suffisso sull'indirizzo (#29)


Ciao ho inserito una correzione.
Puoi rifare un test e farmi sapere se adesso funziona?

**Comment by ClaudioSalerno** [comment]
Ciao,

il valore SN1 è presente nel lotto che vi ho inviato , vedi prot. Domanda 821185326, prot. Richiesta: 821186627.

Il valore “SNC” ( senza numero civico)  non è presente nel lotto, ma l’ho trovato a DB, così come “SN” ( senza numero).



Da: DanRic [mailto:notifications@github.com]
Inviato: giovedì 22 novembre 2018 09:27
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 Bis - Ricerca fornitura con suffisso sull'indirizzo (#29)


Ciao,
com'è uscito fuori il valore SNC e SN1? Nella documentazione non ne abbiamo traccia e neanche sul file.xml reale che ci hai inviato qualche giorno fa.
lotto_845743033.zip<https://github.com/DanRic/Bonus-idrico/files/2607136/lotto_845743033.zip>

**Comment by DanRic** [comment]
Ciao,
ho inserito una correzione.
Adesso quando si riceve SNC o SN, i dati del civico e suffisso sono nulli sull'RdA.
A db vengono selezionati tutti quei servizi che hanno numero civico nullo e/o suffisso nullo

**Comment by ClaudioSalerno** [comment]
la segnalazione può essere chiusa. grazie
