### ISSUE TITLE
CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#34]
ciao,
ho rieseguito il test Vedi prot, rich: CSTEST3STEP9 e CSTEST3STEP9BIS
L'esito va in rifiutata perchè la fornitura non vene trovata.
Nella Rda è presente la fornitura: 36734304 
Nel primo file con rich: CSTEST3STEP9 - ho inserito come come indiirzzo di fornitura : VIA AVALLANO civico 13, ma poi ho visto nel sitema che il civico è 13 ma c'è anche un suffisso 15, allore ho creato un altro file RdA ( CSTEST3STEP9BIS) mettendo nel civico 13/15 ed il risultato è stato lo stesso ( esito RIFIUTATA ). 

e' possibile fare una verifica ?

**Comment by SteLancio** [comment]
Ciao Claudio,
ho verificato che c'era un problema sulla lettura del civico. Ho installato un adeguamento che va a risolvere questa situazione.

Riprova e fammi sapere.

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
ho verificato ed acquisito la rchiesta CSTEST3STEP9TRIS.
L'esito è sempre RIFIUTATA
Errore: siu_sgate_controlli_rda.trova_fornitura: Non sono stati trovati servizi
Il civico nella Rda è 13 / 15 ( cos' come nel DB )

**Comment by SteLancio** [comment]
Ho eseguito delle verifiche e ho visto che in:

VIA AVALLANO
sigvia: 1519
sigloc: 70
interno: 1 
civico: 13
suffisso: 15
edificio: 0

l'intestatario del servizio è VALTER MARTINOTTI:

![image](https://user-images.githubusercontent.com/44225241/48790871-9de2e900-ecf0-11e8-96b3-8abcc05d7882.png)

Mentre nell'RdA che hai caricato c'è ALBINA BIANCARDI:

![image](https://user-images.githubusercontent.com/44225241/48790905-b4894000-ecf0-11e8-9afc-98a9317b8ffc.png)

Per questo motivo il servizio non viene trovato.
Che select utilizzi per estrarre i dati?

Ciao,
Stefano

**Comment by ClaudioSalerno** [comment]
Ciao,
nella Rda c’è:

[cid:image005.jpg@01D48111.1A192670]

A sistema:
[cid:image006.jpg@01D48111.1A192670]

Sull’indirizzo c’è:
[cid:image007.jpg@01D48111.1A192670]

Quindi “Martinotti Valter”  non dovrebbe essere preso in considerazione se viene utilizzato anche Nome e Cognome presente nella RdA.

Ciao
Claudio

Da: SteLancio [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 18:20
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)


Ho eseguito delle verifiche e ho visto che in:

VIA AVALLANO
sigvia: 1519
sigloc: 70
interno: 1
civico: 13
suffisso: 15
edificio: 0

l'intestatario del servizio è VALTER MARTINOTTI:

[image]<https://user-images.githubusercontent.com/44225241/48790871-9de2e900-ecf0-11e8-96b3-8abcc05d7882.png>

Mentre nell'RdA che hai caricato c'è ALBINA BIANCARDI:

[image]<https://user-images.githubusercontent.com/44225241/48790905-b4894000-ecf0-11e8-9afc-98a9317b8ffc.png>

Per questo motivo il servizio non viene trovato.
Che select utilizzi per estrarre i dati?

Ciao,
Stefano

**Comment by DanRic** [comment]
Ciao Claudio,
non si vede molto nella mail che hai inviato.
Puoi rimandarla con le immagini?
Prova da GitHub.

Grazie


Daniele Ricci
Analista Programmatore
Tel. 0858080421
Int.  630421
Email: daniele.ricci@eng.it<mailto:daniele.ricci@eng.it>
Engineering Ingegneria Informatica spa
Divisione Energy & Utilities
Via Nazionale per Teramo, 14 64023 Mosciano (TE) - Italy

________________________________
Da: ClaudioSalerno <notifications@github.com>
Inviato: martedì 20 novembre 2018 20:39
A: DanRic/Bonus-idrico
Cc: Subscribed
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)

Ciao,
nella Rda c’è:

[cid:image005.jpg@01D48111.1A192670]

A sistema:
[cid:image006.jpg@01D48111.1A192670]

Sull’indirizzo c’è:
[cid:image007.jpg@01D48111.1A192670]

Quindi “Martinotti Valter” non dovrebbe essere preso in considerazione se viene utilizzato anche Nome e Cognome presente nella RdA.

Ciao
Claudio

Da: SteLancio [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 18:20
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)


Ho eseguito delle verifiche e ho visto che in:

VIA AVALLANO
sigvia: 1519
sigloc: 70
interno: 1
civico: 13
suffisso: 15
edificio: 0

l'intestatario del servizio è VALTER MARTINOTTI:

[image]<https://user-images.githubusercontent.com/44225241/48790871-9de2e900-ecf0-11e8-96b3-8abcc05d7882.png>

Mentre nell'RdA che hai caricato c'è ALBINA BIANCARDI:

[image]<https://user-images.githubusercontent.com/44225241/48790905-b4894000-ecf0-11e8-9afc-98a9317b8ffc.png>

Per questo motivo il servizio non viene trovato.
Che select utilizzi per estrarre i dati?

Ciao,
Stefano

**Comment by ClaudioSalerno** [comment]
[Issue_34.docx](https://github.com/DanRic/Bonus-idrico/files/2601395/Issue_34.docx)

**Comment by ClaudioSalerno** [comment]
Fatto


Da: DanRic [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 21:02
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)

Ciao Claudio,
non si vede molto nella mail che hai inviato.
Puoi rimandarla con le immagini?
Prova da GitHub.

Grazie


Daniele Ricci
Analista Programmatore
Tel. 0858080421
Int. 630421
Email: daniele.ricci@eng.it<mailto:daniele.ricci@eng.it>
Engineering Ingegneria Informatica spa
Divisione Energy & Utilities
Via Nazionale per Teramo, 14 64023 Mosciano (TE) - Italy

________________________________
Da: ClaudioSalerno <notifications@github.com>
Inviato: martedì 20 novembre 2018 20:39
A: DanRic/Bonus-idrico
Cc: Subscribed
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)

Ciao,
nella Rda c’è:

[cid:image005.jpg@01D48111.1A192670]

A sistema:
[cid:image006.jpg@01D48111.1A192670]

Sull’indirizzo c’è:
[cid:image007.jpg@01D48111.1A192670]

Quindi “Martinotti Valter” non dovrebbe essere preso in considerazione se viene utilizzato anche Nome e Cognome presente nella RdA.

Ciao
Claudio

Da: SteLancio [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 18:20
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)


Ho eseguito delle verifiche e ho visto che in:

VIA AVALLANO
sigvia: 1519
sigloc: 70
interno: 1
civico: 13
suffisso: 15
edificio: 0

l'intestatario del servizio è VALTER MARTINOTTI:

[image]<https://user-images.githubusercontent.com/44225241/48790871-9de2e900-ecf0-11e8-96b3-8abcc05d7882.png>

Mentre nell'RdA che hai caricato c'è ALBINA BIANCARDI:

[image]<https://user-images.githubusercontent.com/44225241/48790905-b4894000-ecf0-11e8-9afc-98a9317b8ffc.png>

Per questo motivo il servizio non viene trovato.
Che select utilizzi per estrarre i dati?

Ciao,
Stefano

**Comment by Danieleeee** [comment]
Ciao Claudio,
hai controllato la data inizio e fine agevolazione del servizio intestato a Albina Biancardi?
Forse Stefano ti proponeva l'altro servizio perchè è quello che si avvicina di più alla condizione che il servizio sia attivo a **data inizio agevolazione**

**Comment by ClaudioSalerno** [comment]
Ciao,
il servizio 36734304 ( stato 1/1 ) associato a ALBINA BIANCARDI ha come data inizio fornitura il 10/08/2018 .
La data di inizio agevolazione nella RdA è 01/07/2018 .

Il servizio 2043060 ( stato 2/0) associato a VALTER MARTINOTTI ha come data inizio 06/02/1979 e data fine 10/08/2018.

La Rda ha il flag di “allineamento” a True.

Quindi sembrerebbe che sia stata individuata la fornitura corretta ( quella di Valter Martinotti) che non è quella presente nella richiesta RdA.
Però, se ci ragioniamo un attimo insieme, è corretto che la Rda viene rifiutata ?
Di fatto , è vero che la fornitura di Albina Biancardi nasce dopo l’inizio agevolazione , ma è attiva nel corso dell’agevolazione.
Per cui rifiutando la richiesta il bonus non va ne a una ne all’altra.
Mentre invece , a mio avviso spetterebbe a Albina Biancardi che , è vero che “nasce” dopo l’inizio agevolazione, ma ha l’Allineamento a True e secondo quanto riportato nella determina anche se la fornitura è attiva dopo l’inizio di agevolazione, è come se lo fosse per cui il bonus va calcolato come se fosse attiva alla data di inizio agevolazione.

[..] da ASR
Domanda idrica presentata il 16 luglio 2018, ammessa dal Comune il 18 luglio e trasferita in pari data al gestore, il gestore per la validazione ha a disposizione il periodo compreso fra il 18 luglio ed il 1 settembre giorno in cui deve restituire un esito a SGAte. Il richiedente risulta già titolare di bonus elettrico e/o gas con periodo di agevolazione 1 maggio 2018 al 30 aprile 2019, la fornitura idrica è attiva al 1 settembre 2018, ma non era attiva all’1 maggio 2018. Il periodo di agevolazione idrico sarà allineato a quello elettrico e gas, quindi la data inizio agevolazione sarà anche per l’idrico il 1 maggio 2018 indipendentemente dal fatto che a quella data la fornitura idrica fosse attiva o no.
[..]

Non so cosa ne pensate, eventualmente allarghiamo la discussione anche agli altri colleghi coinvolti.

Ciao
Claudio



Da: Danieleeee [mailto:notifications@github.com]
Inviato: martedì 20 novembre 2018 21:32
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)


Ciao Claudio,
hai controllato la data inizio e fine agevolazione del servizio intestato a Albina Biancardi?
Forse Stefano ti proponeva l'altro servizio perchè è quello che si avvicina di più alla condizione che il servizio sia attivo a data inizio agevolazione

**Comment by Danieleeee** [comment]
Ciao Claudio, 
quello da te descritto è il comportamento che c'era prima che Stefano implementasse la logica richiesta dall'anomalia [27](https://github.com/DanRic/Bonus-idrico/issues/27).
Adesso viene preso il servizio attivo alla data inizio agevolazione anche se subentrato.
A mio avviso l'anomalia 27 non era da assecondare dato che il comportamento del programma era coerente con quanto condiviso in fase di Analisi dei Requisiti. Senza contare che ti aspettavi che fosse attivata l'agevolazione su un servizio diverso da quello segnalato in RdA e che trovava corrispondenza con i dati nella rete del Gestore (via, nome, cognome).
Cambiare la logica "al volo" come stiamo facendo per alcune delle anomalie che ci segnali, produce più problemi di quanti ne risolve.
A mio avviso la correzione dell'anomalia 27 deve essere eliminata così che tutto continui a funzionare correttamente come prima, compresa l'anomalia corrente.

**Comment by ClaudioSalerno** [comment]
Ciao Daniele,
Mi confronto internamente e vi faccio sapere.

Claudio


Inviato dal mio dispositivo Huawei

-------- Messaggio originale --------
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)
Da: Danieleeee
A: DanRic/Bonus-idrico
CC: Salerno Claudio ,Author


Ciao Claudio,
hai controllato la data inizio e fine agevolazione del servizio intestato a Albina Biancardi?
Forse Stefano ti proponeva l'altro servizio perchè è quello che si avvicina di più alla condizione che il servizio sia attivo a data inizio agevolazione

**Comment by ClaudioSalerno** [comment]
ciao,
l'issue #27  è diversa dal questo caso perchè si riferisce a subentro su stessa anagrafica, per cui è corretto che l'agevolazione venga corrisposta sempre all'utenza attiva.
Questo è stato condiviso in fase di analisi anche con Paola.

Questa segnalazione invece tratta 2 servizi che non hanno in comune l'anagrafica . Tra l'altro nome e cognome ed indirizzo nella RdA permettono di trovare la fornitura che a maggior ragione ha il flag di allineamento a true nella Rda, per cui va considerata come se fosse attiva alla data di agevolazione , anche se "nasce" dopo.

**Comment by ClaudioSalerno** [comment]
Ciao,

GRAZIE!.

ho eseguito un test ( fornitura 36734304 – Prot. Rich: CSTEST3STEP9TRIS , allineamento True ) e sembra che la modifica funzioni … mi riservo domani di fare un altro test.

Siamo nel caso di subentro su anagrafica diversa con ultimo servizio della catena con data inifor ( 10/08/2018) > data inizio agevolazione ( 01/07/2018 ).
Il servizio precedente 2043060 ha data inifor 06/02/1979 e data finfor 10/08/2018.

claudio


Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 21 novembre 2018 18:03
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] CCAM: F1 BIS - TEST3 STEP 9 - VERIFCA STATO FORNITURA (#34)


Ciao ho inserito una correzione.
Puoi rifare un test e farmi sapere se adesso funziona?
