### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Indirizzo non trovato per CAP generico a sistema e CAP puntuale nella RDA

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#36]
Ciao,
nel sistema in corrispondenza della Localita VERBANIA ( 156) , c'è il CAP Generico 28900 , nelle Rda ci sono diversi CAP specifici ( ad esempio 28922 ) .

Il controllo scarta l'indirizzo perchè non trova corrispondenza.
Come si può risolvere ? dove si deve intervenire per specificare i diversi CAP per via/zona ?

grazie

**Comment by DanRic** [comment]
Ciao Claudio,
a sistema abbiamo il cap specifico.
Come mai SGAte non riesce a mandarci il cap specifico? Chi ha fatto la richiesta di agevolazione non conosce il cap di dove vive?

**Comment by ClaudioSalerno** [comment]
Ciao,
è esattamemte il contrario .. il cliente ci passa il CAP specifico , mentre nel sistema c'è il CAP generico .
Ora impostando il CAP Specifico nella località 156 ( Verbania ) da 28900 a 28922, ci troviamo che soddisfiamo un RdA che ha questo CAP, ma un'altra che è sempre a Verbania, ma ha un CAP diverso ( 28921 ad esempio ) viene scartata.

**Comment by SteLancio** [comment]
Ciao Claudio,
dopo le ultime modifiche eseguite, è possibile chiudere questa segnalazione?

**Comment by ClaudioSalerno** [comment]
La segnalazione può essere chiusa.

Grazie


Da: SteLancio [mailto:notifications@github.com]
Inviato: martedì 27 novembre 2018 18:09
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - Indirizzo non trovato per CAP generico a sistema e CAP puntuale nella RDA (#36)


Ciao Claudio,
dopo le ultime modifiche eseguite, è possibile chiudere questa segnalazione?
