### ISSUE TITLE
ACQUA NOVARA: F1 Bis - TrovaFornitura - Servizio non trovato

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#37]
Ciao,
rilevo dverse RdA in RIFIUTATA per Servzio non trovato.

Guardando la funzione: TrovaFornitura --> findServizio()  vedo che nelle where condition c'è';
]..]
       and upper(nvl(ana_nome,'??')) = upper(coalesce(prda.nome,ana_nome,'??'))
       and upper(nvl(ana_cognome,'??')) = upper(coalesce(prda.cognome,ana_cognome,'??'))
       and upper(nvl(ana_ragsoc,'??')) = upper(coalesce(prda.denom_cond_fc, ana_ragsoc,'??')) -- SL Del. 897/17
[..]
mi chiedevo se la condizione di "AND" sia corretta ? 
A mio avviso dovrebbero messe in AND nome e cognome in OR con ragsoc.

Magari mi sbaglio, ma potete prendere in considerazione la mia proposta ?
vedere esempio: prot.rich: 816293218
Richiedente: cognome: COSTA nome: CHERUBINA MARIA GRAZIA 
VIALE GIUSEPPE AZARI , 9

A DB c'è: ana_codana : 95720 - nome: null - cognome: COSTA CHERUBINA MARIA GRAZIA 
ragione sociale: COSTA CHERUBINA MARIA GRAZIA

Grazie

**Comment by DanRic** [comment]
Ciao Claudio,
la select credo sia corretta così.
Sintetizzando la select cerca il nome se viene inserito in RdA, altrimenti va avanti, lo stesso vale per cognome e ragione sociale. Se vengono inseriti in RdA vengono cercati nell'anagrafica, altrimenti no.
Mi sembra che si tratti di un problema di dati valorizzati male a DB, non credo sia corretto valorizzare solo il cognome con (cognome+ragione sociale) e allo stesso modo la ragione sociale =(cognome+ragione sociale) . 
Per quanto riguarda il codice fiscale, si è deciso di verificarlo in un controllo specifico con un proprio codice errore (KO3), come definito anche da normativa. 
Si è sempre sostenuto di dover trovare la fornitura per indirizzo. 
Se si vuole cambiare la logica del programma bisogna rivedere l'analisi.

**Comment by DanRic** [comment]
Io avrei utilizzato molto di più il codice utente invece di sperare di trovarlo da indirizzo ed anagrafica.
Purtroppo in fase di analisi si è deciso di procedere su altra strada.

**Comment by DanRic** [comment]
Il fatto che il codice anagrafico non sia univoco a livello nazionale importa poco. 
La bolletta la invia il gestore e nel DB del gestore al quale si invia l'RdA quel codice esiste ed è univoco. 
Magari se lo inviano ad altro gestore non trova corrispondenza....ma non ci interessa coprire queste casistiche.
Se controllo il CF quando devo verificare la fornitura, il KO3 che comunica "codice fiscale non corrispondente" è inutile. Tanto vale eliminarlo visto che se trovo la fornitura con il CF vuol dire che il CF esiste e non avrò mai KO3.
E' da condividere con il gruppo per vedere cosa ne pensa.

**Comment by ClaudioSalerno** [comment]
Il controllo del KO3 sul CF rimane,vorrà dire che non scatterà quando individuo la fornitura tramite CF,

Quindi lascerei tutto invariato ed aggiungerei , come proposto, la ricerca della fornitura tramite il CF, se poi coincide  e permette di trovare la fornitura tanto meglio , se non coincide si rifiuta la RdA così come è ora.

**Comment by DanRic** [comment]
Scrivi quanto detto sopra a tutto il gruppo.
Se per Stefania e Paola va bene, procedo con lo sviluppo.

**Comment by ClaudioSalerno** [comment]
OK .. ho inviato mail

**Comment by ClaudioSalerno** [comment]
Ciao,
non capisco perchè mi scarta la RdA ( prot, rich: 809172200 ).

Eseguendo la query su WKF_log:
SGATE_CONTROLLI 00000016>SGATE_CONTROLLI findServizio 05/67/41280/156//
SGATE_CONTROLLI 00000017>SGATE_CONTROLLI COUNT 0

Lanciando la query:
Select  ser_ute,ser_dp, -- PDR
            ser_puntopresa,
            ser_codser,
            ser_datainifor,
            ser_datafinfor,
            ser_tipo_pdr,              
            ser_ucnumciv ,                                
            ser_ucscala ,                  
            ser_ucinterno,                 
            ana_sog_cfisc,              
            ana_nome,                 
            ana_cognome,
            nvl(ser_datacont,sysdate),     
            ser_codcat_uso,               
            null, --CONSUMO_ANNUO_STOR      
            null, --CLASSE_CONTATORE        
            null, --FASCIA_CLIMATICA        
            'OK', --esito                   
            null, --msgerr                
            null, --PARIVA_IS               
            'N',
            t.ser_statoserv,
            t.ser_stato_cont
      from serviz t, gesana g
     where t.ser_ute      = :UTE  
       and nvl(t.ser_ucnumciv, 99999) = coalesce(to_number(:CIVICO), t.ser_ucnumciv, 99999)
       and ( (:SUFFISSO is null) or (UPPER(t.ser_ucsuffisso) = UPPER(:SUFFISSO) ) ) -- SL Del. 897/17
       and t.ser_ucsigvia = :SIGVIA 
       and t.ser_ucsigloc = :SIGLOC 
       and t.ser_codana = ana_codana 
       and upper(nvl(ana_nome,'??')) = upper(coalesce(:NOME,ana_nome,'??'))
       and upper(nvl(ana_cognome,'??')) = upper(coalesce(:COGNOME,ana_cognome,'??'))
       and upper(nvl(ana_ragsoc,'??')) = upper(coalesce(:Ragione_sociale, ana_ragsoc,'??')) -- SL Del. 897/17
       and coalesce(trim(t.ser_ucscala), trim(:SCALA), 'K')   = coalesce(trim(:SCALA), trim(ser_ucscala), 'K')   --PG
       and coalesce(trim(t.ser_ucinterno), trim(:INTERNO),'K') = coalesce(trim(:INTERNO), trim(ser_ucinterno), 'K') --PG 
       and t.ser_codsersub is null; 

vengono estratte 18 righe.
Tra queste c'è quella con ANA_NOME null e ANA_COGNOME: RICELLA CHRISTIAN ( che è il richiedente della RdA )

**Comment by SteLancio** [comment]
Ciao Claudio,
dopo le ultime modifiche eseguite, è possibile chiudere questa segnalazione?

**Comment by ClaudioSalerno** [comment]
Le verifiche eseguite finora hanno avuto esito positivo.
Mi riservo fare ulteriori verifiche.
