### ISSUE TITLE
ACQUA NOVARA: F1Bis - Trova fornitura - Prot. rich. 816973188

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#38]
La Rda in oggetto viene rifiutata e nel log viene riportato un codice SIGVIA che non corrisponde alla via passata in RdA. 
Nella Rda c'è VIA TANARO, che è associata al Servizio 73914505 con anagrafica 50085945 - PISANO' MANUELA con ubicazione in VIA TANARO , 22 ( codice via 5504) localita TRECATE ( 149).
Il log mi segnala invece che il SIgVia è 5148.
Questo codice via corrisponde a VIA TEVERE

IL codice via corretto è: 5504 in localita 149 ed effettivamemte risulta che al civico 22 , c'è appunto PISANO' MANUELA.

e' possibile fare una verifica per piacere ?
Grazie
claudio

**Comment by ClaudioSalerno** [comment]
ciao, 
credo di aver trovato il problema...
è il campo a NULL su DVI_DES_100 che crea il problema alla funzione UTL_MATCH.edit_distance_similarity() .  
A Sistema ci sono solo 21 record che il campo DVI_DES_100 valorizzato ed una di queste è quella con codice via 5148 ( estratta dalla prima select ). 
Ho infatti forzato il campo DVI_DES_100 con VIA TANARO ( come il des_30) ed ora la prima select mi estrae 2 record compreso quello giusto.
Ho rieseguito il controllo ed ora la richiesta va in ACCETTATA !!!

Per cortesia , Considerate quindi come poter corrreggere .. la funzione .. 
GRAZIE

**Comment by SteLancio** [comment]
Ciao Claudio,
abbiamo installato una modifica che dovrebbe risolvere il problema segnalato.
Puoi riprovare a ricontrollare massivamente tutte le RdA che venivano scartate per servizio non trovato?

Grazie,
Stefano

**Comment by ClaudioSalerno** [comment]
la segnalazione si può chiudere, Grazie
