### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Controllo Stato Fornitura 

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#42]
ciao,
disattivando il controllo "STATO_FORNITURA" ,  le RdA  che hanno la data limite 01/01/2019 rimangono in ACQUISITA e non evolvono in ACCETTATA/RIFIUTATA/IN VERIFICA.

Es. Prot.Rich: 846498647 Data limite 01/01/2019 - data ini Agevolazione : 01/01/2019
Mi aspettavo che essendo "spento" il controllo, la RdA venisse comunque controllata anche se la data limite/data inizio agev non è ancora "scaduta".

E' possibile fare una verifica urgente ?

Grazie
Claudio

**Comment by SteLancio** [comment]
Ciao Claudio,
il controllo "STATO_FORNITURA" verifica se il servizio è attivo o meno alla data inizio agevolazione.
La logica che esclude il controllo delle RdA, per le quali data ini agev è maggiore di sysdate,non è disattivabile eliminando i controlli.
Considera che inizialmente avevate richiesto di non elaborare tutte le RdA prima di due mesi +1gg dalla data ricezione.

Fammi sapere se posso chiudere la seguente issue.

Ciao,
Stefano

**Comment by ClaudioSalerno** [comment]
Ciao Stefano,
fornisco alcuni razionali per rendere più ciaro il problema.
In ACQUA NOVARA su 617 Rda , ne rimangono un ACQUISITA 167 perchè hanno una data limite o al 01/12/2018 o al 01/01/2019, quindi non ancora pronte per essere processate.
La determina stabilisce che per dare un KO2  (STATO FORNITURA) il Gestore può darlo solo se la foritura non è Attiva alla data di inizio Agevolazione . 
LA data di inzio agevolazione/data limite è la data in cui il Gestore può comunicare gli esiti a SGAte.
Questo vuol dire che potrà farlo solo l'ultimo giorno utile, ovvero il 01/01/2019 .
Questo vuol dire  il Gestore dovrebbe controllarsi 167 RdA tutte in un giorno. 
Per evitare questo abbiamo inserito il parametro STATO_FORNITURA pe dare al Gestore la possibilità di controllare lo stesso le Rda , senza tener conto dello stato.
Nel caso in cui ci sia il flag di "Allineamento" a True, anche se la sysdate non ha superato la data limite, il controllo viene fatto lo stesso ( e qui è effettivamente così e funziona correttamente).

Quindi se disattivo il parametro , mi aspetto che la RdA venga processata/controllata.
E' una decisione che spetta al Gestore,
Fammi sapere se ti è chiara la logica e se riesci ad inserire il controllo.

Grazie
Claudio

**Comment by DanRic** [comment]
Ciao Claudio,
la logica da te descritta è stata scartata.
In fase di analisi si è deciso di non considerare la data limite come vincolo per controllare le RdA, ma la data inizio agevolazione. Questo ti ha permesso di elaborare la maggior-parte delle RdA acquisite, anche se la data limite non è stata raggiunta.
Le restanti RdA non possono essere controllate perchè non possiamo prevedere quale sarà lo stato del servizio in data futura. Questo vincolo è stringente e non dovrebbe essere ignorato dato che non abbiamo le rettifiche: una comunicazione sbagliata non potrà essere corretta.
Attualmente non esistono parametri da modificare per consentire di controllare un servizio da attivare in data futura.
La tua richiesta è nata da una reale esigenza del cliente o per testare l'elaborazione delle altre RdA?
Aggiungo anche @pgasparroni nel caso voglia darci consigli in merito.

**Comment by ClaudioSalerno** [comment]
Ciao Daniele,

aggiungo Stefania e Alina con la quale abbiamo condiviso la richiesta.

Per facilitare la lettura di tutti, riporto il testo della issue:
Segnalazione iniziale da parte mia:
ciao,
disattivando il controllo "STATO_FORNITURA" , le RdA che hanno la data limite 01/01/2019 rimangono in ACQUISITA e non evolvono in ACCETTATA/RIFIUTATA/IN VERIFICA.
Es. Prot.Rich: 846498647 Data limite 01/01/2019 - data ini Agevolazione : 01/01/2019
Mi aspettavo che essendo "spento" il controllo, la RdA venisse comunque controllata anche se la data limite/data inizio agev non è ancora "scaduta".
E' possibile fare una verifica urgente ?
Risposta:
Ciao Claudio,
il controllo "STATO_FORNITURA" verifica se il servizio è attivo o meno alla data inizio agevolazione.
La logica che esclude il controllo delle RdA, per le quali data ini agev è maggiore di sysdate,non è disattivabile eliminando i controlli.
Considera che inizialmente avevate richiesto di non elaborare tutte le RdA prima di due mesi +1gg dalla data ricezione.
Fammi sapere se posso chiudere la seguente issue.
--------------------------------------------
Ciao Stefano,
fornisco alcuni razionali per rendere più chiaro il problema.
In ACQUA NOVARA su 617 Rda , ne rimangono un ACQUISITA 167 perchè hanno una data limite o al 01/12/2018 o al 01/01/2019, quindi non ancora pronte per essere processate.
La determina stabilisce che per dare un KO2 (STATO FORNITURA) il Gestore può darlo solo se la foritura non è Attiva alla data di inizio Agevolazione .
LA data di inzio agevolazione/data limite è la data in cui il Gestore può comunicare gli esiti a SGAte.
Questo vuol dire che potrà farlo solo l'ultimo giorno utile, ovvero il 01/01/2019 .
Questo vuol dire il Gestore dovrebbe controllarsi 167 RdA tutte in un giorno.
Per evitare questo abbiamo inserito il parametro STATO_FORNITURA pe dare al Gestore la possibilità di controllare lo stesso le Rda , senza tener conto dello stato.
Nel caso in cui ci sia il flag di "Allineamento" a True, anche se la sysdate non ha superato la data limite, il controllo viene fatto lo stesso ( e qui è effettivamente così e funziona correttamente).
Quindi se disattivo il parametro , mi aspetto che la RdA venga processata/controllata.
E' una decisione che spetta al Gestore,
Fammi sapere se ti è chiara la logica e se riesci ad inserire il controllo.
Al di la della data da utilizzare ( se data limite o data inizio agevolazione, che per la maggior parte delle 168 RdA coincide) , se il gestore decide di NON controllare lo stato della fornitura e  di assumersi l’onere di riconoscere il Bonus anche se ad esempio oggi il servizio è attivo ma  potrebbe NON esserlo alla data (limite o iniagev), è una sua scelta.
Il parametro STATO_FORNITURA è stato introdotto apposta.
Se è attivo, allora lo stato della fornitura verrà controllato alla data ( limite/iniagev) , se è disattivo, la RdA deve essere processata anche se la data ( limite/iniagev) non è ancora passata.

L’esigenza è reale.
Non possiamo controllare 168 RdA solo l’ultimo giorno, soprattutto in questa fase che ce ne sono tante e tutte insieme.

Inoltre, vista anche la mole di dati , ma soprattutto l’acquisizione per la prima volta di un file reale, possiamo trovarci di fronte a eventuali motivazioni di scarto che ,ne in Fase 1 ne durante i test delle F1Bis , abbiamo intercettato e prima di andare in chiusura CR vorrei essere sicuro che copriamo , non dico il 100% delle casistiche ma almeno il  90%.

Ciao
Claudio


Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 28 novembre 2018 20:19
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - Controllo Stato Fornitura (#42)


Ciao Claudio,
la logica da te descritta è stata scartata.
In fase di analisi si è deciso di non considerare la data limite come vincolo per controllare le RdA, ma la data inizio agevolazione. Questo ti ha permesso di elaborare la maggior-parte delle RdA acquisite, anche se la data limite non è stata raggiunta.
Le restanti RdA non possono essere controllate perchè non possiamo prevedere quale sarà lo stato del servizio in data futura. Questo vincolo è stringente e non dovrebbe essere ignorato dato che non abbiamo le rettifiche: una comunicazione sbagliata non potrà essere corretta.
Attualmente non esistono parametri da modificare per consentire di controllare un servizio da attivare in data futura.
La tua richiesta è nata da una reale esigenza del cliente o per testare l'elaborazione delle altre RdA?
Aggiungo anche @pgasparroni<https://github.com/pgasparroni> nel caso voglia darci consigli in merito.
