### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Filtro per Data Presentazione Domanda

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#43]
Ciao,
il filtro in oggetto sembrerebbe non funzionare .. è possibile fare una verifica per cortesia ?

Grazie
Claudio
[ACQUA_NOVARA_Filtro_ricerca_Data_Presentazione_Domanda.docx](https://github.com/DanRic/Bonus-idrico/files/2632688/ACQUA_NOVARA_Filtro_ricerca_Data_Presentazione_Domanda.docx)

**Comment by ClaudioSalerno** [comment]
ciao,
scusate .. ma credo di aver capito ... il filtro estrae tutte le Rda con data >= alla data presentazione domanda.
Me lo confermate ?
se è così si può chiudere la segnalazione.
Grazie
Claudio

**Comment by SteLancio** [comment]
Ciao Claudio,
si confermo.

Stefano
