### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Prot. Rich. 845905367

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#45]
Ciao,
non riesco a capire la motovazione dello scarto della richiesta in oggetto.
Si tratta di una Centralizzata.

il codice via c
[LOG_Controllo_03-12-2018_193416.xlsx](https://github.com/DanRic/Bonus-idrico/files/2640771/LOG_Controllo_03-12-2018_193416.xlsx)
orretto 253  ( CSO CAVALLOTTI)  nel log il codice via è 2991 (VIA MAGALOTTI )
E' possibile fare una verifica ?

Grazie

**Comment by DanRic** [comment]
Ciao Claudio,
come detto in precedenza nel log viene riportata l'ultima via controllata e non trovata.
Avendo inserito tolleranza al 50% può capitare che ci siano vie che non ti sembrano uguali a quella presente in RdA.
Il servizio non viene trovato perchè in RdA c'è denominazione condominio = 'GIANNI FORMAGGIO', mentre in anagrafica la ragione sociale è 'FORMAGGIO GIANNI' .
Non avendo nome e cognome non possiamo cercare la ragione sociale trasmutando l'ordine dei due elementi cercandoli prima in un senso e poi in quello inverso.

**Comment by ClaudioSalerno** [comment]
Ciao,
non mi è chiara la risposta ... 

Nella richiesta c'è  CORSO CAVALLOTTI, 9 che a sistema esiste.
Cosa centra VIA MAGALOTTI ?

Inoltre chiedo se è possibile introdurre nel CRuscotto il campo denominazione  condominio che se fosse stata visibile ci avrebbe permesso di fare anche altri ragionamenti.

**Comment by DanRic** [comment]
Stiamo provvedendo a far vedere la denominazione condominio.
Via Magalotti viene presa in esame perchè combacia al 50% con la via che hai inserito in RdA.

**Comment by DanRic** [comment]
Abbiamo inserito la nuova colonna sulla form di gestione RdA per visualizzare anche la Denominazione Condominio
