### ISSUE TITLE
ACQUA NOVARA: F1 BIS - Prot.Rich.- 820694701

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#46]
ciao,
per cortrsia è possibile fare una verifica ?

SI tratta di una centralizzata , IN VERIFICA, associa il nome e cognome di una fornitura che on centra nulla.
IL codice servizio trovato è effettovamete nella VIA fornitta ella RdA , ma il nome e cognome corrisponde ad una trova servizio che si trova in una via diversa.

[ACQUA_NOVARA_F1BIS_Prot_rich-820694701.docx](https://github.com/DanRic/Bonus-idrico/files/2642936/ACQUA_NOVARA_F1BIS_Prot_rich-820694701.docx)

**Comment by DanRic** [comment]
A quale servizio ti riferisci dei due?

**Comment by ClaudioSalerno** [comment]
la seconda BRASOLA ITALO ( dove lo prende ? ) non corrisponde all'intestatario del servizio: 71066543
