### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Prot.RIch: 820365609

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#47]
Ciao,
rilevo una associazione Servizi che mi sembra sbagliata in una richiesta CENTRALIZZATA IN VERIFICA.

In pratica la richiesta è in VIA CUSTODI, 9

Il controllo identifica 3 servizi ma andando  a verificare l'ubicazione della fornitura di quei 3 servizi, sono in VIA CUSTOZA.

E' possibile fare una verifica ?

Grazie
Claudio

[ACQUA_NOVARA_F1BIS_Prot_rich-820365609.docx](https://github.com/DanRic/Bonus-idrico/files/2643088/ACQUA_NOVARA_F1BIS_Prot_rich-820365609.docx)

**Comment by DanRic** [comment]
Si, la via è quella indicata in RdA.
Inseriamo una correzione per visualizzare il nuovo nome della via effettivamente presente sul servizio.

**Comment by DanRic** [comment]
Ho fatto la correzione, adesso viene messa la via corretta:
![1](https://user-images.githubusercontent.com/43675808/49434254-10a19900-f7b4-11e8-932b-5bc1339116ed.png)

Esci dalla procedura visto che ho rilanciato dei package a DB e potrebbero invalidarti delle elaborazioni.

Ciao
