### ISSUE TITLE
ACQUA NOVARA: F1 Bis- Invio Esito a SGAte dopo da IN VERIFICA a ACCETTATE

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#48]
Ciao,
ci siamo accorti che le CENTRALIZZATE che erano IN VERIFICA, dopo aver selezionato il Servizio corretto e posto la Rda in ACCETTATA, generando il file degli esiti per Sgate, l'esito viene posto in KO ( tra l'altro senza motivazione ).

Rif, prot rich: 820480545, 834020271, 846566339, 846581769.

E' possibile fare una verifica ?
Grazie
Claudio

**Comment by ClaudioSalerno** [comment]
Integro aggiungendo anche la richiesta 820694701 ed ho verificato che nella tabella SIU_SGATE_RCH_AGEV il campo RAS_STATO_RDA rimane senpre in KO.

Operazioni eseguite : 
stato iniziale: IN VERIFICA
Selezione del servizio corretto
cambio stato da IN VERIFICA in ACCETTATA + F10
Invio esito a SGAte

**Comment by DanRic** [comment]
La correzione è stata inserita.
Puoi uscire dalla procedura e fare una prova.

**Comment by DanRic** [comment]
Non importa che l'esito sia in KO quando va in ACQUISITA.
Verifica com'è l'esito quando va in ACCETTATA.

**Comment by ClaudioSalerno** [comment]
dopo averla portata in ACCETTATA e generato il file degli sito x SGAte, nell'XML lo stato è KO.

**Comment by DanRic** [comment]
Ripristinata e ricontrollata.
L'esito è OK

**Comment by DanRic** [comment]
non è andata neanche IN VERIFICA

**Comment by ClaudioSalerno** [comment]
veramente lo avevamo fatto più volte .... perchè ora non va più  IN VERIFICA ma direttamente in ACCETTATA ?
cosa è cambiato da  2 ore fa ad ora ? E' stato fatto fatto qualche aggiornamento ?

**Comment by DanRic** [comment]
Si, quelli che ci hai segnalato questa mattina.
Probabilmente è la correzione #46 che ho fatto per trovare il nome corretto del Servizio.
Il servizio che ti ha trovato va bene o non ti convince?

**Comment by ClaudioSalerno** [comment]
Il servizio trovato va bene... strano, perchè prima uscenod e rietrando abbiamo portao la richeista da IN VERIFICA a ACQUISITA, eseguito il Controllo la RdA era andata IN VERIFICA trovando 2 servizi,
Selezioato il servizo corretto abbiamo portato la RdA da IN VERIFICA in ACCETTATA e trasmesso l'esito a SGATE e ci siamo accorti che la RdA trasmette un esito KO .
La mia domanda è : è correttp che una RdA IN VERIFICA ponga il campo RAS_STATO_RDA in KO ? Non vrrei che è proprio questo stato che poi in resettandosi , genera poi l'esito KO verso SGAte.

**Comment by DanRic** [comment]
Non è corretto che rimanga in KO ed è stata fatta una correzione.
Volevo sapere se la correzione ha funzionato per chiudere l'anomalia.

**Comment by ClaudioSalerno** [comment]
la correzione sembra che non abbia fuzionato.
Ti descrivo il test che ho fatto Rda prot.rich: 820365609
Posto lo stato da IN VERIFICA ad ACQUISITA 
pulito a mano il KO ( RAS_STATO_RDA)
eseguito il Controllo
L'RdA va in IN VERIFICA
lo stato va in KO

**Comment by DanRic** [comment]
Questo è corretto, lo stato IN VERIFICA è un KO che necessita di correzioni da parte dell'operatore.
Forse non ho capito bene la tua segnalazione.
Lamentavi il fatto che l'esito inviato a SGAte era un KO e doveva essere OK?
O non ti piace il fatto che quando l'RdA va in IN VERIFICA, venga posto un esito (momentaneo) = KO sulla Rda?

**Comment by ClaudioSalerno** [comment]
Allora .. provo a spiegarmi .. semma chiamami al telefono 3407161609 ..
L'RdA va IN VERIFICA, l'operatore sceglie il servzio a cui associare la RdA.
Pone lo stato in ACCETTATA e trasmette l'esito a SGATE.
Nell'XML dell'esito verso SGAte, lo stato è KO.
Ma perchè, se l'operatore a fronte di una IN VERIFICA dovuta al controllo che trova più servizi, seleziona il servizio corretto, pone la RdA in ACCETTATA, mi aspetto che l'esitp verso SGAte sia un OK e non un KO!

**Comment by DanRic** [comment]
Non è questo l'operatività del programma.
Se l'RdA va IN VERIFICA, dopo che ha selezionato il servizio deve portare l'RdA in ACQUISITA e rifare tutti i controlli.
Questo perchè il controllo per trovare il servizio non è l'unico controllo che facciamo. Se poni l'RdA in ACCETTATA salti tutti i controlli che ci sono dopo. Ed è corretto che ti da un KO visto che hai saltato l'esecuzione di tutti i controlli successivi.

**Comment by DanRic** [comment]
Da quello che mi dici mi viene il sospetto che non ci fosse un'anomalia ma semplicemente un utilizzo sbagliato del programma.
