### ISSUE TITLE
Errore controllo CF

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#5]
Ciao,
sto controllando l'RdA 24232.
Mi restituisce KO quando controlla lo stato della fornitura.
Non dovrebbe essere così perchè:
- data inizio agevolazione = 27-JUL-18
- data inizio fornitura = 28-FEB-96

Credo che l'errore sia in questa parte del codice:
```sql
if p_rda.data_ini_agev <= sysdate then
       -- se allineamento non presente oppure N 
       if nvl(p_rda.ALLINEAMENTO, 'N') = 'N' then
         -- si esegue il controllo data inizio fornitura (valorizzata) <= dataInizioAgevolazione
          if v_data_ini <= p_rda.data_ini_agev then
            cod_Err_SIU := 102;
            return 'KO';
          end if;
      end if;
end if;
```

**Comment by SteLancio** [comment]
Ok, verifico e ti aggiorno.

**Comment by SteLancio** [comment]
Il package non era aggiornato. Dopo averlo aggiornato ho riprovato a controllare l'rda 24232 riscontrando il seguente rifiuto:

![image](https://user-images.githubusercontent.com/44225241/47077943-7042e580-d202-11e8-80c4-7ff58aee1f6d.png)

Errore:

`siu_sgate_controlli_rda.codice_fiscale: Errore nella ricerca dei servizi in SIU_SGATE_SERV_RDA. Errore= ORA-06502: PL/SQL: numeric or value error: character to number `

Verifico e ti aggiorno.

**Comment by SteLancio** [comment]
C'era un problema sulla dichiarazione della var del codfis che ho provveduto a correggere.
Ho riprovato riscontrando esito positivo:

![image](https://user-images.githubusercontent.com/44225241/47078931-a5e8ce00-d204-11e8-9366-feda95a77dd3.png)

![image](https://user-images.githubusercontent.com/44225241/47078875-8baef000-d204-11e8-9bd3-ded0a51d845e.png)

Chiudo la segnalazione.
