### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Acquisizione Esito KO da SGAte - Prot. Rich. 820694701

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#51]
Ciao,
abbiamo eseguito il seguente Test:
Inviato esito a SGAte con OK
Ricevuto Esito da SGAte KO

Nel Log viene segnalato il seguente messaggio di errore:
siu_sgate_gestione_xml.carica_esito_sgate - Errore generico(POS: Acquisisco dati esito n¿ 1). ERR: ORA-30625: method dispatch on NULL SELF argument is disallowed

[LOG_Acquisizione_Esiti_05-12-2018_0838.xlsx](https://github.com/DanRic/Bonus-idrico/files/2647733/LOG_Acquisizione_Esiti_05-12-2018_0838.xlsx)

E' normale che dia questo errore ?

**Comment by DanRic** [comment]
Ciao,
puoi inviarmi il file che stai acquisendo?

**Comment by ClaudioSalerno** [comment]
[Esiti_da_SGAte_82064701.zip](https://github.com/DanRic/Bonus-idrico/files/2647841/Esiti_da_SGAte_82064701.zip)

per allegare il file ho dovuto cambiare l'estensione da XML a zip 
prima di aprirlo per cortesia rinominalo in .xml

**Comment by DanRic** [comment]
Ho inserito la correzione.
Puoi riprovare? Prima esci e rientra dalla procedura.
Grazie

**Comment by ClaudioSalerno** [comment]
Intervento positivo.
la Rda è andata IN VERIFICA
l'abbiamo passata in ACQUISITA e poi riesguito il Controllo.
Inviato esito OK a SGAte
Ricevuto Esito OK da SGAte
La RdA è in CONFERMATA
Puoi chiudere la segnalazione.
Grazie
