### ISSUE TITLE
ACQUA NOVARA: F1 Bis- Definizione Parametro dei Controlli -CODICE_CONDOMINIALE

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#52]
Ciao,
per cortesia è possibile specificare quale sia a funzionaità del controllo CODICE_CONDOMINIALE ?
DI default è impostato a N , mettendolo a S cosa dovrebbe controllare ?

Grazie mille
Claudio

**Comment by DanRic** [comment]
Si riferisce a controlli inseriti nella fase1 e non più utilizzati.
Se pensi che possa creare problemi li eliminiamo definitivamente.

**Comment by ClaudioSalerno** [comment]
Grazie eliminalo.

Evitiamo cose inutili.


Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 5 dicembre 2018 10:43
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis- Definizione Parametro dei Controlli -CODICE_CONDOMINIALE (#52)


Si riferisce a controlli inseriti nella fase1 e non più utilizzati.
Se pensi che possa creare problemi li eliminiamo definitivamente.

**Comment by DanRic** [comment]
Eliminati
