### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Dimensionamento griglia Cruscotto Rda

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#53]
In fase di collaudo il cliente mi chiede se è possibile ridimensionare alcuni campi in visualizzazione.

Ad esempio il campo della via ( AREA) è un po piccolo e spesso la denominazione della via non viene visualizzata per intero ed è necessario posizionarsi con il cursore e scorrere la stringa.
Il campo de civico è molti più grande del dovuto, così come interno ed altro.

So che è una richiesta che comporta una miglioria ...
Dato che oggi al 99% ci daranno un OK alla chiusura delle CR .. possiamo fare qualcosa ?

Grazie

**Comment by SteLancio** [comment]
Ciao Claudio,
modifiche appena installate. Controlla se adesso la dimensione è ok.

**Comment by ClaudioSalerno** [comment]
Si può chiudere . GRAZIE !!
