### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Cambio di stato da IN VERIFICA in ACQUISITA

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#54]
Ciao,
scusa una Info ... nel caso in cui una RdA mi va IN VERIFICA perchè trova più servizi ... quando la passo in ACQUISITA , non dovrebbe cancellare i dati dei servizi visualizzati ?

**Comment by DanRic** [comment]
No, perchè nel caso in cui hai selezionato un servizio salta i controlli per ri-calcolarli e va ai successivi.

**Comment by ClaudioSalerno** [comment]
Non ho selezionato alcun servizio

Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 5 dicembre 2018 10:52
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - Cambio di stato da IN VERIFICA in ACQUISITA (#54)


No, perchè nel caso in cui hai selezionato un servizio salta i controlli per ri-calcolarli e va ai successivi.

**Comment by DanRic** [comment]
Lo so, dicevo che nel caso in cui li hai selezionati, salta ai controlli successivi.
Se non li hai selezionati li cancella quando la controlli e quindi ricalcoli i servizi.
Non abbiamo messo una funzionalità che sbianca i servizi se non sono selezionati e riporti la RdA in ACQUISITA. Non pensavamo che la cosa potesse creare problemi al cliente.

Inoltre il fatto di avere i servizi vecchi ti indica che l'hai già elaborata e trovato quei servizi.

**Comment by ClaudioSalerno** [comment]
Non ho capito a cosa ti riferisci con:

Inoltre il fatto di avere i servizi vecchi ti indica che l'hai già elaborata e trovato quei servizi.


Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 5 dicembre 2018 10:59
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - Cambio di stato da IN VERIFICA in ACQUISITA (#54)


Lo so, dicevo che nel caso in cui li hai selezionati, salta ai controlli successivi.
Se non li hai selezionati li cancella quando la controlli e quindi ricalcoli i servizi.
Non abbiamo messo una funzionalità che sbianca i servizi se non sono selezionati e riporti la RdA in ACQUISITA. Non pensavamo che la cosa potesse creare problemi al cliente.

Inoltre il fatto di avere i servizi vecchi ti indica che l'hai già elaborata e trovato quei servizi.

**Comment by DanRic** [comment]
Come fai a distinguere una RdA ACQUISITA e mai controllata da una che hai controllato, mandato IN VERIFICA e poi ripristinato in ACQUISITA? In questo modo lo puoi sapere.

**Comment by ClaudioSalerno** [comment]
La risposta mi piace .

Questa la puoi chiudere

Da: DanRic [mailto:notifications@github.com]
Inviato: mercoledì 5 dicembre 2018 11:05
A: DanRic/Bonus-idrico
Cc: ClaudioSalerno; Author
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - Cambio di stato da IN VERIFICA in ACQUISITA (#54)


Come fai a distinguere una RdA ACQUISITA e mai controllata da una che hai controllato, mandato IN VERIFICA e poi ripristinato in ACQUISITA? In questo modo lo puoi sapere.
