### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Prot.Rich: 809677673  Via non trovata

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#55]
ciao,
la Rda presenta un indirizzo in VIA MARCONI, 60
A sistema c'è VIA GUGLIELMO MARCONI, 60
La % di tolleranza è impostata al 50%
La query per verificare la % da un risultato del 53% ( quindi dovrebbe passarla )

select UTL_MATCH.edit_distance_similarity(upper('VIA GUGLIELMO MARCONI'), upper('VIA MARCONI')) 
from dual;

DOpo aver fatto il controllo, cliccasndo sul"S" , mi fa vedere 3 servizi e tutti in VIA MURATA ( che non centra proprio niente)
ieri era stata fatta una modifica e sembrava essere andata bene ma forse c'è ancora qualcosa che non va.

Puoi cortesemente fare una verifica ? 
Risolto questa questione dovremmo essere a posto.

**Comment by DanRic** [comment]
Ciao,
la procedura funziona correttamente.
Il problema è la percentuale di tolleranza che è troppo bassa.
Viene presa anche VIA MURATA. Che ha quei servizi su quel CAP (solo prime 3 cifre), civico ed istat.
Magari se fornivano la denominazione condominio non avevamo problemi.

**Comment by ClaudioSalerno** [comment]
Ciao,
non mi torna quello che mi dici ..

ma se viene fornita VIA MARCONI e a sistema ho VIA GUGLIELMO MARCONI
IL civico coincide 60
il codice ISTAT mi identifica il comune 
Il CAP è quello corretto
la % del controllo è 53% 
non capisco come mai va in VERIFICA ...

Inoltre cosa centra VIA MURATA ?

**Comment by DanRic** [comment]
Se vuoi invece di prendere quello con maggiore coincidenza, li prendo tutti.
Però avrai comunque la RdA in verifica, con più servizi mostrati. Poi selezioni quello che ti sembra giusto.

**Comment by DanRic** [comment]
In questo modo però molti altri servizi che ti trova senza mandarli in verifica, poi andranno in verifica se la percentuale di coincidenza è così bassa (50%)

**Comment by ClaudioSalerno** [comment]
Ma non capisco pechè viene presa VIA MURATA !!

Ma se passo una stringa con VIA MARCONI e a sistema ho VIA GUGLIELMO MARCONI , cosa centra VIA MURATA ?!

**Comment by ClaudioSalerno** [comment]
Questa segnalazione mi sta invalidando il collaudo ... cerca d fare qualcosa per cortesia .. così coem è mi rimane difficile da sostenere

**Comment by ClaudioSalerno** [comment]
e se in ultima istanza prima di scartare ... verifichiamo il codice utente ??? 
lo so che è un paradosso

**Comment by DanRic** [comment]
La logica del codice utente non si modifica fino a quando non si decide di comune accordo che è la strada giusta. Casomai ne parliamo domani.
Poi scusa...è troppo facile se usiamo il codice utente!

**Comment by ClaudioSalerno** [comment]
lascia perdere per il momento il codice utente .. la richiesta è stata fatta in un momento di "panico" ...

cerca di risolvermi al questione della VIA ... così come è è difficilmente sostenibile .
Ripeto non riesco a far digerire al cliente che se passo VIA MARCONI e a sistema ho VIA GUGLIELMO MARCONI non è logico che mi vada a cercare una fornitira con una via cha non centra nulla (VIA MURATA)

**Comment by DanRic** [comment]
Ho inserito una correzione.
Puoi uscire e rientrare dalla procedura e riprovare.

**Comment by ClaudioSalerno** [comment]
abbiamo riprovato.
la richeista va ancora in RIFIUTATA per fornitura non trovata 
"non ci sono servizi trovati ...."

**Comment by ClaudioSalerno** [comment]
nel log mi mette che la VIA con cui ha provato a cercare la fornitura è  Sig. Via= 45256 che "PIAZZA DEL LAVATOIO" ... cosa centra con VIA MARCONI ?

**Comment by DanRic** [comment]
Ciao Claudio,
ho inserito la modifica.
Adesso va IN VERIFICA:
![1](https://user-images.githubusercontent.com/43675808/49523210-92272300-f8a9-11e8-9288-18b432c3ea13.png)

**Comment by DanRic** [comment]
Ciao Claudio,
ho inserito una ulteriore correzione.
Adesso trova la via corretta
