### ISSUE TITLE
ACQUA NOVARA: F1 Bis - Prot.Rich: 846281602 - Fornitura RIFIUTATA

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#56]
ciao,
non capisco perchè mi viene rifiutata questa Rda:
la RDA è in VIA CALVARI, 12 istat 003106 (NOVARA) - cap 28100 
la forntura in VIA CALVARI,12  a NOVARA cap 28100

Grazie

**Comment by ClaudioSalerno** [comment]
integro ..
viene fornita anche la Denominazione del condominio: A.T.C PIEMONTE NORD

**Comment by ClaudioSalerno** [comment]
cavolo !!! 
è vero non lo avevo notato !!

Ma per un "."  !!
Non possiamo introdure una % di tolleranza anche per questo campo ?
Il clente mi dice che è assurdo

**Comment by DanRic** [comment]
Forse nella fase2. 
Non so se il cliente è abituato ad inserire i dati in scioltezza come sta facendo per le vie di SGAte ed il sistema capisce tutto da solo.
Dagli sviluppi che ho fatto fin'ora di solito si cerca coincidenza sui dati... non che più o meno.. a senso... si capisce.
Tutte queste capriole sempre perchè si è deciso di non usare il codice utente.

**Comment by DanRic** [comment]
Ho inserito una percentuale di tolleranza del 90% sulla denominazione del condominio.
Esci dalla procedura e rifai un test.
Ciao

**Comment by ClaudioSalerno** [comment]
ho fatto il test e ora la RdA va inn ACCETTATA
Non vedo però il parametro di tolleranza delle denominazione condominio a sistema ( lo hai messo all'interno del programma ?)

**Comment by DanRic** [comment]
@SteLancio Puoi inserire tu il parametro della tolleranza sulla denominazione del condominio?
Adesso è cablata a 90
