### ISSUE TITLE
ACQUA NOVARA: F1 Bis - ProtRich. 820420139 - Estrae VIA ma non tutti gli utenti sul civico

### ISSUE THREAD

**Issue by ClaudioSalerno** [DanRic/Bonus-idrico#57]
[Prot_Rich_820420139.docx](https://github.com/DanRic/Bonus-idrico/files/2649303/Prot_Rich_820420139.docx)

La via la estrae corretta, la RdA va IN VERIFICA ma i servizi che estrae sono di altre Vie pur estraendo un servzio ( in stato 3/0 ) della via giusta VIA ANTONIO GRAMSCI

**Comment by SteLancio** [comment]
C'era un problema sulla scrollbar dei servizi (non scrollava in basso).
Ho provveduto a correggerli e adesso vedrai tutti i servizi trovati (compreso quelli sulla VIA GRAMSCI) che ti aspettavi che in realtà abbiamo verificato che non sono 5, ma 3.. perchè comunque 2 sono subentrati --> ser_codsersub is null.

Stiamo cercando di migliorare la ricerca del servizio per fare in modo che i servizi trovati sulle vie siano meno.

**Comment by DanRic** [comment]
Ciao,
abbiamo inserito un miglioramento.
Adesso trova i servizi corretti.
Rifai un tentativo e facci sapere.

**Comment by ClaudioSalerno** [comment]
Grazie.


Fatemi sapere quando avremo una situazione stabile .. ovvero quando il pck che state modificando mi permette di fare delle verifiche .

Ciao
Claudio

Inviato dal mio dispositivo Huawei

-------- Messaggio originale --------
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - ProtRich. 820420139 - Estrae VIA ma non tutti gli utenti sul civico (#57)
Da: SteLancio
A: DanRic/Bonus-idrico
CC: Salerno Claudio ,Author


C'era un problema sulla scrollbar dei servizi (non scrollava in basso).
Ho provveduto a correggerli e adesso vedrai tutti i servizi trovati (compreso quelli sulla VIA GRAMSCI) che ti aspettavi che in realtà abbiamo verificato che non sono 5, ma 3.. perchè comunque 2 sono subentrati --> ser_codsersub is null.

Stiamo cercando di migliorare la ricerca del servizio per fare in modo che i servizi trovati sulle vie siano meno.

**Comment by ClaudioSalerno** [comment]
Perfetto ...grazie!!!

Ora vedo se dal treno riesco

Inviato dal mio dispositivo Huawei

-------- Messaggio originale --------
Oggetto: Re: [DanRic/Bonus-idrico] ACQUA NOVARA: F1 Bis - ProtRich. 820420139 - Estrae VIA ma non tutti gli utenti sul civico (#57)
Da: DanRic
A: DanRic/Bonus-idrico
CC: Salerno Claudio ,Author


Ciao,
abbiamo inserito un miglioramento.
Adesso trova i servizi corretti.
Rifai un tentativo e facci sapere.

**Comment by ClaudioSalerno** [comment]
ciao,
sono riuscito a collegarmi dal treno , sto facendo le verifiche.
Vedo che nel pulsante S quando vengono visualizzati i servizi, viene messo l'indirizzo senza il civico.
E' possibile inserirlo ? Questo agevola l'operatore a selezionare il servizio corretto.
grazie mille
