### ISSUE TITLE
Tolleranza Civico TEST6

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#58]
Ciao,
ho notato che la tooltip della TOLLERANZA CIVICO è sbagliata, dice che si possono inserire più valori separati da ;
![1](https://user-images.githubusercontent.com/43675808/52954666-0b9fbf00-338b-11e9-82c9-cf73ddc88240.png)

Dovrebbe essere consentito solo un valore.
Sembra che il controllo sul civico non sia presente nei package.

**Comment by SteLancio** [comment]
La tooltip vale per tutti i campi e non è parametrizzabile per singola opzione.

**Comment by DanRic** [comment]
Possiamo mettere un tooltip generica che vada bene per tutti i campi?
Tipo: "Valore assegnato al parametro"

**Comment by SteLancio** [comment]
Modifica eseguita.
