### ISSUE TITLE
controllo CHECK_SUFFISSO TEST5

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#59]
Ciao,
non trovo il controllo sul nuovo parametro CHECK_SUFFISSO.
![2](https://user-images.githubusercontent.com/43675808/52956650-1e68c280-3390-11e9-80a7-8809b421031a.png)

**Comment by SteLancio** [comment]
I controlli erano salvati su una vs del package in locale poichè SIU_SGATE_CONTROLLI_RDA serviva a Cimini per una correttiva.
Li ho appena riportati nuovamente.

Ciao,
Stefano
