### ISSUE TITLE
Form Gestione Rich. Agev

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#6]
Ciao,
è possibile ordinare le RdA visualizzate per data inserimento decrescente?
Magari utilizza anche 2 date, tipo inserimento e datastato...
![1](https://user-images.githubusercontent.com/43675808/47076627-71264800-d1ff-11e8-9f67-e0ad59cae9a4.png)

**Comment by SteLancio** [comment]
Risolto inserendo order --> data stato desc.
