### ISSUE TITLE
Filtro Tipologia Fornitura TEST8

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#60]
Ciao,
ho controllato la logica del nuovo filtro "Tipologia Fornitura".
Sia sul pkg siu_sgate_automatismi che su siu_sgate_gestione_xml, il filtro è messo così:
```sql
AND (p_tipologia_forn is not null and ras_tipo_fornitura = p_tipologia_forn)
```
Mentre dovrebbe essere così
```sql
AND (p_tipologia_forn is null or ras_tipo_fornitura = p_tipologia_forn)
```

**Comment by SteLancio** [comment]
Si, me ne sono accorto anch'io facendo i test per le rettifiche ed avevo già provveduto a correggere il problema.
