### ISSUE TITLE
Filtro tipologia fornitura per i controlli delle cessazioni TEST8

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#61]
Ciao,
puoi inserire il filtro della tipologia fornitura anche nella sezione delle cessazioni?
![1](https://user-images.githubusercontent.com/43675808/52960324-d601d280-3398-11e9-83b5-4f16d8d21b68.png)

**Comment by SteLancio** [comment]
Questo filtro abbiamo concordato che non va inserito.

**Comment by DanRic** [comment]
OK
