### ISSUE TITLE
Lista Id Acquisizione e Nome file

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#62]
La lov per selezionare l'Id Acquisizione non dovrebbe mostrare valori di ID duplicati.
C'è da correggere la select casomai eliminando le colonne che ci fanno estrarre più record per lo stesso Id Acquisizione.

![1](https://user-images.githubusercontent.com/43675808/52966095-b7a2d380-33a6-11e9-9ca6-5e52f617f8a2.png)

Lo stesso discorso vale per la lov del "Nome file"

**Comment by SteLancio** [comment]
Ok, fatto. Riprova adesso

**Comment by DanRic** [comment]
La lista del nome file è risolta.
La lov dell'Id Acquisizione no, mostra questi errori:
![1](https://user-images.githubusercontent.com/43675808/53011724-567c0e00-3441-11e9-9a8a-b1e4fca3128d.png)
![2](https://user-images.githubusercontent.com/43675808/53011730-5bd95880-3441-11e9-892c-973e52b0a8b6.png)

**Comment by SteLancio** [comment]
Riprova adesso

**Comment by DanRic** [comment]
OK
