### ISSUE TITLE
Errori in acquisizione file delle cessazioni

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#65]
Ciao,
acquisendo delle cessazioni dalla form Acqusizione e Controllo RDA, se la cessazione viene scartata vengono prodotti 2 file di log, uno dei quali sembra riferito all'estrazione delle cessazioni:

![1](https://user-images.githubusercontent.com/43675808/53237628-73118380-3697-11e9-8acc-04612dc1843c.png)

Allego file di log ed XML.
[file.zip](https://github.com/DanRic/Bonus-idrico/files/2893568/file.zip)

**Comment by DanRic** [comment]
Se correggo il file.xml e lo faccio acquisire, vengono inserite nel sistema.
Ma produce sempre i 2 file di log.

Nel primo rimane scritto "non conferme con lo schema":
![1](https://user-images.githubusercontent.com/43675808/53238104-c0422500-3698-11e9-89aa-a231d5b972f7.png)

Riallego tutti i file prodotti.
[file_2.zip](https://github.com/DanRic/Bonus-idrico/files/2893603/file_2.zip)

**Comment by DanRic** [comment]
Controlla anche come memorizza i protocolli Segnalazione e Richiesta di riferimento.
Non li memorizza correttamente e non riesce ad agganciare la RdA.
![4](https://user-images.githubusercontent.com/43675808/53238735-62164180-369a-11e9-99de-16be574e83e7.png)

**Comment by DanRic** [comment]
Controlla il nome delle colonne sul secondo file di log (da inglobare nel primo):
![1](https://user-images.githubusercontent.com/43675808/53238923-ea94e200-369a-11e9-9461-23712e3e0aca.png)

**Comment by SteLancio** [comment]
Ho corretto i problemi segnalati.
In particolare, per quanto riguarda la produzione del file csv doppio, è un comportamento voluto se l'opzione seguente è attiva:

![image](https://user-images.githubusercontent.com/44225241/53251387-cea23800-36bc-11e9-953a-441217b3e3ad.png)
