### ISSUE TITLE
LOG Contollo Cessazioni

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#66]
Il controllo delle cessazioni non produce un file di log.

**Comment by SteLancio** [comment]
Il problema dovrebbe essere risolto. Riprova e fammi sapere se adesso è ok

**Comment by DanRic** [comment]
Puoi mettere un _ dopo SCS?
Attualmente il nome del file è LOG_Controllo_SCS01-03-2019_0928, fallo diventare 
LOG_Controllo_SCS_01-03-2019_0928.
Grazie

**Comment by SteLancio** [comment]
Fatto.
