### ISSUE TITLE
Errori collegati al controllo delle Cessazioni

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#67]
Ciao,
controllando la cessazione DR3 viene prodotto il log ma non sono riportati gli errori sulla tab che si visualizza premendo il pulsante "E"
![1](https://user-images.githubusercontent.com/43675808/53627941-0bfd4d00-3c0a-11e9-9598-fe2089862b2d.png)

[LOG_Controllo_SCS01-03-2019_0928.zip](https://github.com/DanRic/Bonus-idrico/files/2918719/LOG_Controllo_SCS01-03-2019_0928.zip)

**Comment by SteLancio** [comment]
Era sbagliato il protocollo della segnazione inserito nella tabella degli errori.
Puoi caricare una nuova cessazione e farla andare in errore in modo tale da verificare se i valori dei protocolli vengono inseriti correttamente sugli errori?

Grazie

**Comment by DanRic** [comment]
Ho rifatto il test ma l'errore rimane:
![1](https://user-images.githubusercontent.com/43675808/53630357-29cdb080-3c10-11e9-84a3-8928402d0ea9.png)

**Comment by SteLancio** [comment]
Riprova adesso.

**Comment by DanRic** [comment]
Quando ripristino una Cessazione da rifiutata ad Acquisita non vengono sbiancati gli errori.
Puoi verificare?

**Comment by DanRic** [comment]
Ignora, era un problema di refresh dei dati.

**Comment by SteLancio** [comment]
Riprova adesso

**Comment by DanRic** [comment]
Adesso non vengono mostrati gli errori, per nessuna, anche per quelle in rifiutata

**Comment by SteLancio** [comment]
Riprova adesso. Ho tolto la colonna del protocollo rich cessazione in quanto non serviva

**Comment by SteLancio** [comment]
Più che tolto la colonna, ho tolto la visibilità sulla pagina

**Comment by DanRic** [comment]
Ciao Stefano,
l'errore c'è ancora:
![1](https://user-images.githubusercontent.com/43675808/53960177-da8ef080-40e5-11e9-99df-0d9bc6c17d64.png)
Non so se dipende dal pulsante "E" o dal fatto che quando la cessazione DR5 va in RIFIUTATA non vengono registrati gli errori.
Comunque credo che un minimo giro di test andrebbe fatto prima di dire che l'anomalia è stata risolta.

**Comment by SteLancio** [comment]
Sulla DR5 non vedo errori in tabella:

![image](https://user-images.githubusercontent.com/44225241/53961052-04491700-40e8-11e9-8d90-1eb0bedf9a1f.png)

I test sono stati eseguiti. Come mai è andata in rifiutata? Hai verificato il log?

**Comment by DanRic** [comment]
I test era da farlo facendo generare gli errori e verificare se si visualizzavano.
Questa cessazione, è andata in rifiutata e non vengono mostrati errori. 
Secondo me c'è qualcosa che non va.
Sul log viene riportato l'errore:
_Il codice fiscale della RDA di riferimento della segnalazione di cessazione SGAte non e' valorizzato_

E' più di una settimana che stiamo su questa anomalia...non riusciamo ad uscirne?!

**Comment by SteLancio** [comment]
Si ma il problema è che l'errore non è stato proprio inserito nella tabella.
Quando ho eseguito il test gli errori erano presenti. 

Verifico

**Comment by DanRic** [comment]
Riesci a correggere questa anomalia?  
E fare un test controllando una cessazione e verificando che si vedono gli errori?
Non vorrei che correggendo quest'ultima anomalia poi gli errori ci sono ma non si vedono e siamo punto a capo.

**Comment by SteLancio** [comment]
Non credo che si tratti di un'anomalia perchè ripeto, funzionava tutto correttamente.
Non vorrei che i package sono stati sovrascritti o ce n'è qualcuno scompilato.

Sto verificando

**Comment by SteLancio** [comment]
Il problema dipende dal fatto che nella tabella della codifica degli errori non è presente l'indice:

![image](https://user-images.githubusercontent.com/44225241/53963464-afa89a80-40ed-11e9-9650-699a6c40d0a4.png)

Essendo l'aggdati stato rilanciato più volte nei giorni scorsi per gli sviluppi della fase 23 in corso, si è presentato questo problema. Intanto ho bonificato l'errore , riprova e fammi sapere.

Sto verificando la presenza dell'indice

**Comment by SteLancio** [comment]
Indice creato.

**Comment by DanRic** [comment]
Gli errori si vedono, però ancora non funziona correttamente.
Sul log i messaggi d'errore vengono duplicati:
![1](https://user-images.githubusercontent.com/43675808/53964263-49bd1280-40ef-11e9-90f7-96c5f3e005d0.png)
Ed anche in tabella gli errori sono doppi:
![2](https://user-images.githubusercontent.com/43675808/53964292-55a8d480-40ef-11e9-8712-0e0724cbdb43.png)
Sembra che l'indice appena creato non faccia benissimo il suo lavoro.
C'è da correggere indice e produzione di errori doppi.
A correzione anomalia puoi rifare il giro complete per vedere che funziona tutto?

**Comment by SteLancio** [comment]
L'indice è il medesimo già presente ed archiviato nella cr iniziale SIUWEB_CR_14839 - H2O: SGAte bonus idrico (DB). 
Ho corretto il problema sull'errore doppio riportato in fase di interrogazione del dettaglio dell'errore della cessazione e adesso il log è corretto:

![image](https://user-images.githubusercontent.com/44225241/53967787-247fd280-40f6-11e9-9a09-b718a222ba79.png)

**Comment by SteLancio** [comment]
Ho rifatto un test ricontrollandole tutte e adesso è tutto ok.

**Comment by DanRic** [comment]
OK.
Oltre a quello segnalato ci sono queste due correzioni da fare.
- Puoi riportare nel campo causale la descrizione dell'errore? Tipo "Data decorrenza non valida"?
Attualmente viene scritto su tutti gli errori: "CONTROLLO POST ACQU...."

![2](https://user-images.githubusercontent.com/43675808/53968745-e2f02700-40f7-11e9-8be6-b5b000d3f376.png)

- Puoi allungare la dimensione della colonna SCSG_NOTE? Succeda a volte quando ripristino la RdA da RIFIUTATA in ACQUISITA. Dipende dalla lunghezza dell'errore.

![1](https://user-images.githubusercontent.com/43675808/53968476-652c1b80-40f7-11e9-8f5c-05a3183a0cbe.png)

**Comment by DanRic** [comment]
E' da correggere anche il file di log.
- Elimina la colonna "Protocollo Inoltro", "PDR Domenstico" e "PDR Condominiale".
- Aggiungi una colonna, dopo Prot. Segnalazione: "Prot. Rich. Rif"

**Comment by SteLancio** [comment]
I problemi segnalati dovrebbero essere tutti risolti:

![image](https://user-images.githubusercontent.com/44225241/53973939-f902e500-4101-11e9-9369-70d8d5e18cfb.png)

![image](https://user-images.githubusercontent.com/44225241/53973964-03bd7a00-4102-11e9-8bf1-5a64f59f4246.png)

Compreso il campo note. 

Fammi sapere

**Comment by DanRic** [comment]
Errore DR6:
![1](https://user-images.githubusercontent.com/43675808/53975245-b262ba00-4104-11e9-8038-654bab1acc7b.png)

Non è vero

**Comment by SteLancio** [comment]
Verifico

**Comment by DanRic** [comment]
Forse volevi dire: nessuna richiesta in CONFERMATA/RICONOSCIUTA?

**Comment by SteLancio** [comment]
No, il codice di errore è corretto:

![image](https://user-images.githubusercontent.com/44225241/53975901-2ce00980-4106-11e9-906d-c74a1b9a9071.png)


L'rda associata era in uno stato non CONFERMATA o RICONOSCIUTA.

**Comment by SteLancio** [comment]
Modifica eseguita:

![image](https://user-images.githubusercontent.com/44225241/54024405-010d6400-4198-11e9-9312-699dd9d40a77.png)
