### ISSUE TITLE
Cessazione, controllo codice fiscale

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#68]
Ciao, mi rifiuta la Cessazione con protocollo DR5.
Dice:
_Il codice fiscale   della RDA di riferimento della segnalazione di cessazione SGAte non ¿   valorizzato_
E' da correggere il punto esclamativo rovesciato.
Inoltre non capisco perchè la rifiuta, la RdA 820170794 che voglio cessare ha il codice fiscale uguale a VCHSLV63P68L219A.

**Comment by SteLancio** [comment]
Ho corretto il controllo e modificato il codice. 
L'errore è definito nella tabella SIU_SGATE_CODIF_ERR. Ho provveduto a correggerlo facendo l'update nell'aggdati. 
Riprova adesso e fammi sapere

**Comment by DanRic** [comment]
Ci sono ancora degli errori.
segnala che il codice fiscale delle cessazione non è valorizzato nella cessazione DR5, ma non è vero:
![1](https://user-images.githubusercontent.com/43675808/53970765-b4744b00-40fb-11e9-9136-5d23fd71d112.png)

**Comment by SteLancio** [comment]
Ho corretto il problema ma adesso viene fuori:

![image](https://user-images.githubusercontent.com/44225241/53975006-35374500-4104-11e9-9a4d-c79d3445623f.png)

**Comment by DanRic** [comment]
E non va bene. Che errore è?
E' previsto che restituiamo quell'errore?

**Comment by SteLancio** [comment]
Codice errore 508:

![image](https://user-images.githubusercontent.com/44225241/53975582-6f551680-4105-11e9-8783-48496c3d5c7e.png)


Lo da quando i codici fiscali sono differenti rispetto a quelli dell'rda 

![image](https://user-images.githubusercontent.com/44225241/53975730-d2df4400-4105-11e9-9ce1-4e5904dd31ad.png)

![image](https://user-images.githubusercontent.com/44225241/53975750-e1c5f680-4105-11e9-8985-7cfdfea13c59.png)


Se è sbagliato il controllo lo correggo.

**Comment by DanRic** [comment]
Il controllo va bene, anche il codice.
Riusciamo a far visualizzare una descrizione interna e non quella che inviamo a sgate?
Almeno si capisce che vuol dire incoerenza dei dati.

**Comment by SteLancio** [comment]
Verifico

**Comment by SteLancio** [comment]
Modifica eseguita:

![image](https://user-images.githubusercontent.com/44225241/54024362-dfac7800-4197-11e9-8f68-4966b8802267.png)
