### ISSUE TITLE
Scartate non eliminate quando cambi stato in ACCETTATA

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#7]
Ciao,
l'RdA 24232 è stata portata in accettata ma ne rimane comunque una con lo stesso protocollo nella tabella delle scartate.  
![1](https://user-images.githubusercontent.com/43675808/47089606-7c8a6b00-d221-11e8-8a0f-f5227f7dae5b.png)
Forse cerchi per nome file invece che per protocollo inoltro?

**Comment by SteLancio** [comment]
Come ti dicevo, quella rda è frutto di un mio caricamento errato in quanto inserito con il medesimo rda che stai utilizzando. Ho provveduto ad eliminarla a mano.
