### ISSUE TITLE
Ricezione esiti cessazioni da SGAte

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#70]
Ciao,
acquisendo il file degli esiti da SGAte ho i seguenti errori:

- Il file di log LOG_Acquisizione_Esiti_SCS13-03-2019_1625 non ha l'estensione .csv
- Stacca nel nome del file SCS dalla data. così: SCS_13-03-2019

Nel file csv i campi prodotti non sono corretti.
Ci sono dei punti interrogativi, ce un 1 che non si capisce a casa sia riferito, il nome del file riporta solo il path del file ma non c'è il nome.
Protocollo segnalazione riporta ERR, OK; non è corretto.
![1](https://user-images.githubusercontent.com/43675808/54291729-4de4a680-45ad-11e9-8351-669c7fd41535.png)

Non è riuscito ad elaborare l'esito dei protocolli DR5 e  DR6 ma non si capisce il perchè. Una sta in verifica l'altra è rimasta in ATTESA ESITO.

Allego tutti i file del test:
[Test_esiti.zip](https://github.com/DanRic/Bonus-idrico/files/2962234/Test_esiti.zip)

**Comment by SteLancio** [comment]
Ciao,
i problemi sopra riportati dovrebbero essere tutti corretti. In particolare per quanto riguarda il DR6 il problema era dovuto dall'xml errato mentre la DR5 va in stato IN VERIFICA per il seguente motivo:

![image](https://user-images.githubusercontent.com/44225241/54372336-6a4f1480-467b-11e9-97f8-f8b1efd3c9b0.png)

v_gestControEsitiNeg := NVL(siu_sgate_automatismi.get_param_vari(p_ute, 'MIS-ACE001'), 'N');

Dove 
![image](https://user-images.githubusercontent.com/44225241/54372395-8652b600-467b-11e9-9979-f0d0ec876ec5.png)

Fammi sapere.

**Comment by DanRic** [comment]
Posso chiudere questa anomalia?

**Comment by SteLancio** [comment]
Ti direi di si
