### ISSUE TITLE
Messaggio errore RdA

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#71]
Ciao,
quando vengono mostrati i messaggi d'errore delle RdA la causale è valorizzata sempre con CONTROLLO POST ACQUISIZIONE - CONTROLLI PDR CENTRALIZZATO:
![1](https://user-images.githubusercontent.com/43675808/54689070-1af76100-4b1f-11e9-9153-dbc07d4d0908.png)

Mettici lo stesso messaggio d'errore che metti nella "Descrizione".
Così se uno modifica la descrizione, la causale rimane invariata con il messaggio originale.

Grazie

**Comment by SteLancio** [comment]
Modifica eseguita. Fai una prova e fammi sapere.

**Comment by DanRic** [comment]
C'è qualcosa di scompilato.
sono uscito e rientrato ma non riesco a controllare l'RdA:
![2](https://user-images.githubusercontent.com/43675808/54692587-82b0aa80-4b25-11e9-8111-6896700b27d2.png)

Inoltre ho notato che quando premi il pulsante C di fianco ad una RdA per controllarla, si apre la form di controllo, filtrata per il protocollo RdA che vuoi controllare. Però rimane fleggato anche il controllo delle cessazioni. In pratica controlli solo quella RdA e tutte le cessazioni se ti dimentichi di levare il flag:
![1](https://user-images.githubusercontent.com/43675808/54692698-b4297600-4b25-11e9-9129-b1cfea4d7f5f.png)

**Comment by DanRic** [comment]
Ok
