### ISSUE TITLE
Acquisizione CSV fuori ISEE

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#72]
Ciao,
c'è qualcosa che non va nell'acquisizione dei file fuori ISEE.
Ho elaborato il TASK91098 dove sul log mi dava errore sul formato delle date.
Ho corretto le date ed ha fallito la seconda acquisizione (TASK91100) dove dice che ho chiave doppia su SIU_SGATE_RICH_AGEV.
Però continuo a non vedere nessuna RdA sul cruscotto.

**Comment by SteLancio** [comment]
Problema corretto. Ho ricaricato il file:

![image](https://user-images.githubusercontent.com/44225241/54939982-1faa8380-4f2a-11e9-8f16-c37314a9be8b.png)


![image](https://user-images.githubusercontent.com/44225241/54939866-e540e680-4f29-11e9-8a9e-cafd05568e11.png)
![image](https://user-images.githubusercontent.com/44225241/54939971-16b9b200-4f2a-11e9-9578-a1ba1cc759ff.png)

Di seguito il risultato dell'elaborazione:

![image](https://user-images.githubusercontent.com/44225241/54940007-2cc77280-4f2a-11e9-840b-abdb6f2fdfc0.png)

![image](https://user-images.githubusercontent.com/44225241/54940042-3ea91580-4f2a-11e9-88a2-21d28a187049.png)

![image](https://user-images.githubusercontent.com/44225241/54940118-5d0f1100-4f2a-11e9-9208-6909e5eac489.png)

Fammi sapere.

**Comment by SteLancio** [comment]
Ho visto che le date che venivano riportate nel file di log delle richieste elaborate sono in un formato errato. Ho corretto il problema.

**Comment by DanRic** [comment]
Ok.
Però mi aspettavo che l'ultimo servizio centralizzato (62904294) andasse in rifiutato visto che non è attivo a data inizio agevolazione.
E' terminato il 27/06/2018 e la data inizio agevolazione è 15/03/2109.

**Comment by SteLancio** [comment]
Corretto. Riprova e fammi sapere.
