### ISSUE TITLE
Controllo RdA fuori ISEE

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#73]
Ciao,
il pulsante "C" dei controlli funziona anche per le RdA fuori ISEE.

**Comment by SteLancio** [comment]
Riprova adesso.

**Comment by DanRic** [comment]
Ok, quando si preme il bottone delle cessazioni e rettifiche, cerca di mettere il messaggio anche per le RdA normali quando non ci sono dati da visualizzare.
Va benissimo anche un messaggio in basso, basta che diamo qualche info:
![1](https://user-images.githubusercontent.com/43675808/54982197-85d6eb00-4faa-11e9-85a7-b6cd7a0ac6c9.png)

**Comment by SteLancio** [comment]
Ok, fatto.
Riprova adesso e fammi sapere
