### ISSUE TITLE
Errore in acquisizione CSV

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#74]
Controlla il log del TASK91109, da quest'errore:
Insert Riga 3 ORA-06502: PL/SQL: numeric or value error: character to number conversion error

**Comment by DanRic** [comment]
L'errore era dovuto al fatto che nel puntopresa c'è un K che non è numerico.
Adesso anche uscendo e rientrando quando acquisisco un file da CSV mi da questo:
![2](https://user-images.githubusercontent.com/43675808/54986659-55e01580-4fb3-11e9-8488-1ece2a814b09.png)

**Comment by SteLancio** [comment]
Si, l'errore sul puntopresa l'avevo visto ma mi aspettavo fosse intercettato meglio. Indago su come mai e verifico anche su questo messaggio che hai adesso.

**Comment by SteLancio** [comment]
Ho eseguito una correzione che dovrebbe dare un messaggio più parlante in caso di formato dati inserito in modo errato.
Per quanto riguarda invece l'errore che hai riscontrato alla pressione del pulsante, era dovuto dal controllo sul nome del file già esistente:

![image](https://user-images.githubusercontent.com/44225241/54988399-a5741080-4fb6-11e9-9436-a5d0c2a6ae58.png)


In particolare mancava una distinct sulla slelect che esegue tale controllo in quanto a sistema, per quello specifico nome file che hai tentato di caricare nuovamente (ovvero TEST_DR_BI_T_4.csv) erano già presenti due righe.

Riprova adesso e fammi sapere.
