### ISSUE TITLE
Gestione KO sbagliata

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#75]
Gli errori sulle righe del CSV, tipo: puntopresa non esistente, non dovrebbero scartare tutto il CSV ma scrivere su ogni riga esito KO e nel dettaglio: "Fornitura INDIVIDUALE (o CONDOMINIALE) non presente nel sistema"

**Comment by SteLancio** [comment]
Infatti dovrebbe essere così, mi dici il task che hai eseguito per il seguente test?

**Comment by DanRic** [comment]
TASK91114

**Comment by SteLancio** [comment]
Problema risolto. Fammi sapere
