### ISSUE TITLE
fuori ISEE Controllo errato fornitura attiva

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#79]
Ciao,
se vedi il TASK91150 ti dice che il servizio 38298630 non è attivo a data inizio agevolazione, ma non è vero.
Cerchiamo di aggiustare il controllo senza introdurre regressioni.
Prima non lo mostrava, adesso lo mostra sempre

**Comment by SteLancio** [comment]
Riprova adesso.

**Comment by DanRic** [comment]
Questo funziona.
**Però** ho acquisito due RdA: BI_855_1 e BI_854_1
Entrambe sullo stesso servizio, entrambe sullo stesso periodo e me le ha acquisite senza battere ciglio.
Non dovrebbe scartare la seconda se ne ho già una per lo stesso periodo?

**Comment by SteLancio** [comment]
La BI_854_1 era su un mio caricamento che ho eliminato. 
Comunque si, il controllo dovrebbe essere eseguito, riprova ad inserire gli stessi dati del protocollo BI_855_1  e fammi sapere se scarta correttamente.
