### ISSUE TITLE
Errore generazione BONUS in stage CCAM (più servizi su singolo indirizzo)

### ISSUE THREAD

**Issue by fidore** [DanRic/Bonus-idrico#8]
Ho generato un file di richiesta con una sola domanda per un'utenza centralizzata e l'ho portata sino all'acquisizione degli esisti da sgate. Ho allora lanciato la generazione del bonus ma ho ottenuto l'errore contenuto nel report allegato.

[FILE_LOG_TASK44249_17102018-142313.log](https://github.com/DanRic/Bonus-idrico/files/2487655/FILE_LOG_TASK44249_17102018-142313.log)

**Comment by fidore** [comment]
Sono andato a vedere la tabella SIU_SGATE_INDIR_CENTR menzionata nel file di log, e ho visto che in realtà il record corrispondente al numero di protocollo che ho fatto esiste.
Nel record esiste anche l'indirizzo esatto della fornitura condominiale che avevo scelto ma il puntopresa è diverso da quello scelto.
Quindi la prima cosa da correggere è l'errore di non esistenza dell'indirizzo perché a non esistere in realtà è la fornitura centralizzata, infatti il puntopresa contenuto nel record del mio protocollo è in realtà individuale.
La seconda cosa è il modo in cui viene recuperato il puntopresa a partire dall'indirizzo della centralizzata. Nell'xml di richiesta non c'è il codice servizio quindi bisogna basarsi solo sull'indirizzo. 
Poiché il servizio centralizzato non ha il suffisso mentre quello individuale che è stato preso ce l'ha, considerando solo i dati richiesti dalla normativa i due indirizzi sono esattamente uguali. Questa situazione è mostrata nella form Gest. Rich. di Agevolazione dove troviamo solo un record.
Al momento della generazione del bonus viene però preso l'altro servizio, forse per un ordinamento alfabetico sulla ragione sociale/cognome || nome.
Secondo me questa situazione deve essere rilevata in fase di controllo e la richiesta messa quindi in stato  "IN VERIFICA" per consentire all'operatore di scegliere la fornitura corretta.
Per favore fatemi sapere quando potrò proseguire i test, per adesso siamo fermi.

**Comment by fidore** [comment]
Inserisco il file XML della richiesta centralizzata:

[TEST_RDA_FD_IBAN_003.xml.txt](https://github.com/DanRic/Bonus-idrico/files/2488082/TEST_RDA_FD_IBAN_003.xml.txt)

**Comment by SteLancio** [comment]
Ciao Daniele,
questa segnalazione penso che possa essere chiusa in quanto testata da Claudio Salerno (issue #18 )

Confermi?

**Comment by DanRic** [comment]
Si. Chiudo
