### ISSUE TITLE
Acquisizione esito Rettifiche

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#82]
Ho acquisito l'esito da SGAte per la Rettifica con protocollo segnalazione R89.
Mi dice che sono stati scartati due esiti, ma ne ho acquisito solo uno:

![1](https://user-images.githubusercontent.com/43675808/55712564-428b6c00-59ef-11e9-9eea-4884d090902e.png

Il file.csv riporta due errori di tipo warning (non dovrebbero essere bloccanti?)
uno dei quali riporta:

> L'esito non e' conforme in quanto e' legato ad una RDA che non e' in uno stato accettabile(ACCETTATA-RIFIUTATA). Stato RDA:

Ma l'RdA si trova in CONFERMATA:
![1](https://user-images.githubusercontent.com/43675808/55712881-d0675700-59ef-11e9-8238-08155198a2a2.png)

Allego file csv prodotto:
[LOG_Acquisizione_Esiti_08-04-2019_1107.zip](https://github.com/DanRic/Bonus-idrico/files/3053570/LOG_Acquisizione_Esiti_08-04-2019_1107.zip)

Inoltre la Rettifica è passata in Confermata e la RdA è rimasta com'era.

**Comment by SteLancio** [comment]
Problema risolto:

![image](https://user-images.githubusercontent.com/44225241/55792873-da598a80-5ac1-11e9-8193-307bb10bd679.png)

**Comment by SteLancio** [comment]
L'rda collegata è andata in 

![image](https://user-images.githubusercontent.com/44225241/55792938-007f2a80-5ac2-11e9-8377-050e0b5a8a86.png)

**Comment by DanRic** [comment]
Ho acquisito il seguente esito per le Rettifiche manuali segnalate alla issue #84 
Non aggiorna niente e non segnala errori. Dice solo che ne ha acquisite 2 (sono 3 esiti).

[esitiDaSGAte.zip](https://github.com/DanRic/Bonus-idrico/files/3074056/esitiDaSGAte.zip)

**Comment by SteLancio** [comment]
Ho appena riacquisito l'esito xml che hai allegato ed il comportamento riscontrato è il seguente:

![image](https://user-images.githubusercontent.com/44225241/56050385-0a1bc300-5d4c-11e9-98e6-7776739fdc45.png)

Nel log vedo quanto di seguito:

![image](https://user-images.githubusercontent.com/44225241/56050405-1dc72980-5d4c-11e9-8beb-8c2cc003da45.png)

**Comment by DanRic** [comment]
Da me l'esito era diverso, ma anche il tuo continua ad essere sbagliato.
La 121 dice che non è in uno stato accettabile, invece sta in confermata e dovrebbe andare in RIFIUTATA.
Tutte le rettifiche sono rimaste in ATTESA ESITO

**Comment by SteLancio** [comment]
Ho inserito le correzioni/logiche che ci siamo detti. Ho riseguito il test riscontrando che adesso le rettifiche vengono aggiornate correttamente:

![image](https://user-images.githubusercontent.com/44225241/56122529-eab2af00-5f72-11e9-81d2-0a757e666266.png)

**Comment by SteLancio** [comment]
Ho ripetuto il test e le rda sono evolute nello stato atteso, ovvero:

Ret:
![image](https://user-images.githubusercontent.com/44225241/56134715-71758500-5f8f-11e9-8cee-bda1d7311a33.png)

RdA:
![image](https://user-images.githubusercontent.com/44225241/56134686-63276900-5f8f-11e9-9fdd-9470c7c7e02d.png)

Ret: 
![image](https://user-images.githubusercontent.com/44225241/56134788-94a03480-5f8f-11e9-8245-fa7df0ec3d4b.png)

RdA:
![image](https://user-images.githubusercontent.com/44225241/56134771-89e59f80-5f8f-11e9-86a7-f03819fd957f.png)

Ret:
![image](https://user-images.githubusercontent.com/44225241/56134837-aeda1280-5f8f-11e9-9a1c-a9177424c8bf.png)


Rda:
![image](https://user-images.githubusercontent.com/44225241/56134813-a5e94100-5f8f-11e9-8202-c9c47e430cc1.png)

**Comment by DanRic** [comment]
Il file di log è scritto male, non vengono rispettate le colonne:
[LOG_Creazione_Esiti_15-04-2019_1633.zip](https://github.com/DanRic/Bonus-idrico/files/3080644/LOG_Creazione_Esiti_15-04-2019_1633.zip)

**Comment by SteLancio** [comment]
C'era un problema legato alla gestione degli scarti inserita in questa vs:

![image](https://user-images.githubusercontent.com/44225241/56143280-8575b280-5fa0-11e9-9b7d-d66b0a8ab307.png)

Ho spostato la parte di codice dentro la gestione degli scarti delle rda e ripetendo il test il log è stato generato senza errori.

**Comment by DanRic** [comment]
La gestione degli scarti, di per se dovrebbe andare bene.
E' corretto che sposti la generazione degli scarti per le RdA solo quando è fleggata la generazione degli esiti per le RdA e non anche adesso per le Rettifiche.
Avvisami quando hai corretto gli errori di formattazione del CSV.

Grazie

**Comment by SteLancio** [comment]
La gestione dell'xml degli scarti è stata spostata dentro alle logiche di selezione del flag rda.
Riprova e fammi sapere se adesso è ok
