### ISSUE TITLE
Rettifica manuale (Inserimento servizio)

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#83]
Ciao, sto provando a rettificare manualmente l'RdA con protocollo richiesta 845565433.
Quando inserisco il servizio non trova i dati dell'indirizzo:
![2](https://user-images.githubusercontent.com/43675808/55715761-b597e100-59f5-11e9-8a01-4e7b1c027d5a.png)

Non valorizza in automatico il flag "Seleziona per bonus" e quindi se salvo mi richiede sempre di inserire il servizio (in realtà gli manca il flag).

Ho inserito il flag, salvato, se ri-premo la "S" per vedere il servizio, non mostra niente:
![1](https://user-images.githubusercontent.com/43675808/55715896-f09a1480-59f5-11e9-8e51-d49d2bb9609b.png)

**Comment by SteLancio** [comment]
Problema risolto:

![image](https://user-images.githubusercontent.com/44225241/55806971-9fffe580-5ae1-11e9-8eb7-463c012efa28.png)
