### ISSUE TITLE
Rettifiche: Codice errore non inserito

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#84]
Ciao ho generato l'esito per 3 rettifiche, una era già presente, le altre le ho inserite io con la gestione manuale.
Il file degli esiti ha solo OK e KO senza errori ne descrizione.
Non avevamo già affrontato questo problema?

[ESITI_RETT_X_SGAte_12-04-2019_1715.zip](https://github.com/DanRic/Bonus-idrico/files/3073939/ESITI_RETT_X_SGAte_12-04-2019_1715.zip)

Inoltre quando si inserisce un errore manualmente, il campo CAUSALE Rimane vuoto:

![2](https://user-images.githubusercontent.com/43675808/56048184-3f71e200-5d47-11e9-8c4c-c078b36ba7c0.png)

**Comment by SteLancio** [comment]
Nel campo causale ho inserito la valorizzazione "Errore inserito manualmente".

**Comment by SteLancio** [comment]
Ho verifcato che le motivazioni dei codici non vengono riportate sul file xml in quanto in fase di inserimento manuale dell'errore della rettifica da form non andiamo a valorizzare la colonne "ESRE_TIPO":

![image](https://user-images.githubusercontent.com/44225241/56129768-4d13ab80-5f83-11e9-8c86-afd0924e2a6a.png)

Le logiche della procedura prevedono l'estrazione quanto di seguito:

 SELECT esre_stato,
                       esre_coderr_sgate
                  FROM SIU_SGATE_ERRORI_SDRE
                 WHERE esre_ute = p_ute
                   AND esre_protocollo_segnalaz = c_rett_acc.prot_segn
                   AND (esre_tipo IN ('B', 'A', 'W') OR esre_stato = 'ERR')

Le strade sono due: o modifichiamo l'inserimento dell'errore in form prevedendo la valorizzazione della colonna ESRE_TIPO oppure modifichiamo la select nella procedura.

Quale delle due è più corretta?

**Comment by DanRic** [comment]
Puoi valorizzare automaticamente esre_tipo = B in fase di inserimento da form.
Puoi prendere la tipologia dell'errore dalla lov che li mostra.
Ciao

**Comment by SteLancio** [comment]
La tipologia dell'errore non è visibile nella lov in quanto non presente nella rispettiva tabella di definizione di codici degli errori.
Il tipo errore credo che sia definito nella tab di definizione dei controlli.

Provvedo a valorizzare automaticamente ESRE_TIPO = B.

**Comment by DanRic** [comment]
Non mostri solo gli errori di tipo B nella select che fai nella lov?
Nella tabella siu_sgate_codif_err c'è il tipo di errore. Tu non la consideri nella lov per mostrare gli errori da inserire?

**Comment by SteLancio** [comment]
Il tipo errore non è in questa tab:

![image](https://user-images.githubusercontent.com/44225241/56135766-b995a700-5f91-11e9-9687-7a0c1a33c76a.png)
****

La select che viene eseguita sulla form per la lov è la seguente:

SELECT SGC_COD_SIU, SGC_TEXT_SIU, SGC_ESITO, SGC_COD_SGATE
from siu_sgate_codif_err
where SGC_ESITO = 'KO'
  and sgc_cod_sgate in (1,2,3,4,5,6,7)
order by sgc_cod_sgate asc
