### ISSUE TITLE
Form Gestione Richieste di Agevolazione chiede sempre se voglio salvare le modifiche

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#85]
Adesso la form Gestione Richieste di agevolazione chiede sempre se vuoi salvare le modifiche, ho aperto la form e cerco di chiuderla:
![1](https://user-images.githubusercontent.com/43675808/56049783-7bf30d00-5d4a-11e9-8c4d-87240ac676dc.png)

**Comment by SteLancio** [comment]
Questo comportamento non riesco a replicarlo. Non è che hai modificato erronemanete qualcosa quando sei entrato?
