### ISSUE TITLE
Inserimento manuale Servizi Rettifiche ed RdA

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#87]
Ciao,
ho notato che inserendo più servizi quando si fa una rettifica crea degli errori.
1. Viene sempre fleggato il genera bonus; dovrebbe essere attivo solo sull'ultima, non su tutte
2. Inserendo più righe non si riesce ad uscire dalla popup e viene sempre chiesto:
![1](https://user-images.githubusercontent.com/43675808/56223523-34cc8b00-606e-11e9-9ab4-f9b186e185ef.png)

3. Le combinazione che non vanno sono tante, provare a giocare con le combinazioni per individuarle.

**Comment by SteLancio** [comment]
Ho inserito una nuova logica che dovrebbe andar bene ma mi riservo di fare ulteriori test domani.

**Comment by SteLancio** [comment]
Ho apportato ulteriori correzioni, riprova adesso.
