### ISSUE TITLE
Rettifica di una RdA Riconosciuta

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#88]
Ciao,
se rettifico una RdA riconosciuta si apre la pop-up per inserire gli errori, ma se premo esci senza inserire niente, me lo fa fare senza mostrare allert.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43675808/56274035-43628300-60fe-11e9-9fbb-af277c9f6791.gif)

**Comment by SteLancio** [comment]
Riprova adesso.

**Comment by DanRic** [comment]
Analizzando i test che mi hanno mandato ci siamo dimenticati un allert che sarebbe da aggiungere.
In pratica quando seleziona la rettifica manuale di una RdA in stato RICONOSCIUTA, devi mostrare questo messaggio prima di passare alla tab delle Rettifiche:
_“Per l’RdA che si vuole Rettificare è già stato calcolato il bonus.
Si vuole proseguire?”_

**Comment by SteLancio** [comment]
L'alert c'è, bisogna verificare come mai non scatta

**Comment by DanRic** [comment]
Ok, fammi sapere.

**Comment by SteLancio** [comment]
Problema risolto. Puoi riprovare?

![image](https://user-images.githubusercontent.com/44225241/56283614-95ad9f00-6112-11e9-870e-727a514f803d.png)

![image](https://user-images.githubusercontent.com/44225241/56283636-a231f780-6112-11e9-9346-df791bd2dfc5.png)
![image](https://user-images.githubusercontent.com/44225241/56284704-94ca3c80-6115-11e9-8a18-bed847989d66.png)
