### ISSUE TITLE
Applicare ricerca RdA al TAB

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#91]
Ciao,
puoi eliminare il tasto "Ricerca" ed attivare la ricerca al tab di ogni campo filtro.
Vale sia per le RdA che per Cessazioni che per Rettifiche.

**Comment by SteLancio** [comment]
Modifica eseguita.

**Comment by DanRic** [comment]
Puoi eliminare il pulsante "Ricerca"?

**Comment by SteLancio** [comment]
Eliminato.
