### ISSUE TITLE
Eliminazione parametrizzazione tipi controlli

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#93]
Ciao, 
cercando i tipi di controlli che posso inserire o filtrare dalla form "Definizione Controlli SGAte".
Volevo filtrare solo i controlli delle cessazioni, premendo f9 sulla lov mi viene mostrato un controllo che non esiste (vecchio del gas) **CESSAZIONE_DIS**.
Puoi eliminarlo?
![1](https://user-images.githubusercontent.com/43675808/56289069-600fb280-6120-11e9-8e59-c5ee7b1a3d1b.png)

**Comment by SteLancio** [comment]
Eliminato:

![image](https://user-images.githubusercontent.com/44225241/56365950-52c2f880-61f2-11e9-998f-9752fc5c7419.png)
