### ISSUE TITLE
Modifica dei dati solo in formato Acquisita

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#94]
Ciao,
i dati della RdA possono essere modificati solo se lo stato è in ACQUISITA.
Adesso si può modificare sempre.

**Comment by DanRic** [comment]
Ho notato che se modifichi 10 campi, l'elaborazione è lenta ogni volta che ti sposti su un campo e:
Quando dai il commit chiede se vuoi confermare le modifiche per ogni campo che hai modificato!
![1](https://user-images.githubusercontent.com/43675808/56294470-635c6b80-612b-11e9-8f3b-d278de8d28a1.png)

**Comment by SteLancio** [comment]
Ho apportato una correzione che dovrebbe risolvere il problema. Fammi sapere se adesso è ok
