### ISSUE TITLE
Visualizzazione codici di errori da selezionare per le Rettifiche

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#95]
Ciao,
puoi rendere più visibili i codici di errore che l'utente può selezionare?
![1](https://user-images.githubusercontent.com/43675808/56296033-044c2600-612e-11e9-8a8a-7f98921e6a4a.png)
Cerchiamo di far vedere la descrizione dell'errore.

Grazie

**Comment by SteLancio** [comment]
Modifica eseguita:

![image](https://user-images.githubusercontent.com/44225241/56366764-2314f000-61f4-11e9-8c0c-c1e12aeb1276.png)
