### ISSUE TITLE
Log Acquisizione RdA

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#98]
Ciao,
acquisendo una RdA viene prodotto un file di log senza i dati dell'RdA (azienda, protocollo, ecc..)

[file.zip](https://github.com/DanRic/Bonus-idrico/files/3137381/file.zip)

**Comment by SteLancio** [comment]
Ho apportato una modifica che dovrebbe risolvere il problema. Nel caso di rda acquisita dovrebbero essere riportati i dati dell'rda acquisita
