### ISSUE TITLE
siu_sgate_controlli_rda_b.sql sbagliato su Serena

### ISSUE THREAD

**Issue by DanRic** [DanRic/Bonus-idrico#99]
Ciao,
su Serena, l'item siu_sgate_controlli_rda_b.sql contiene il package SIU_SGATE_CARICA_BI.

**Comment by DanRic** [comment]
Devo correggere il package e non so da che versione partire.
Siamo a cavallo?

**Comment by SteLancio** [comment]
Su svilh20 c'è la versione con le modifiche di martedì, altrimenti fra poco rientro a casa e accendo il PC e ti recupero la versione

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by DanRic** [comment]
Non riporterei dal cliente la versione con le modifiche di martedì.
Non dovevi finire di testarla? Volevo portare quella prima senza le ultime modifiche.
Per il momento sto lavorando con la versione del cliente che non ha i dettagli della versione.

**Comment by SteLancio** [comment]
Parti da quella del cliente

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by SteLancio** [comment]
A scopo di bck, ho appena ripristinato la vs di martedì:

![image](https://user-images.githubusercontent.com/44225241/57078397-81f76080-6cee-11e9-865d-158b9bd54e61.png)

Ma per le tue correzioni parti dalla vs #31 che dovrebbe essere la stessa presente sul cliente.

**Comment by SteLancio** [comment]
Nella vs #33 ci sono le modifiche eseguite "nella ricava_via_Loc" + le correzioni che mi ha indicato Paola.
